package com.vidyut.company.dto;

public enum CompanyAgentActionType {
    SIMULATE_DEMO_FAULT,
    RESTORE_DEMO_CHARGER,
    PUT_DEMO_CHARGER_IN_MAINTENANCE,
    DISABLE_NEW_BOOKINGS,
    CREATE_MAINTENANCE_TICKET,
    NOTIFY_STATION_MANAGER,
    APPLY_PRICE_RECOMMENDATION
}
