import React, { useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadingView } from '../../src/components/LoadingView';
import { Colors } from '../../src/constants/colors';
import { getCompanyBookings, getCompanyChargers, getCompanyDashboard, updateCompanyBooking, updateCompanyCharger } from '../../src/features/company/company.api';
import { CompanyBooking, CompanyCharger } from '../../src/features/company/company.types';

type Tab = 'BOOKINGS' | 'LIVE' | 'FAULTS';
function money(value: number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0); }

export default function CompanyOperationsScreen() {
  const client = useQueryClient();
  const [tab, setTab] = useState<Tab>('BOOKINGS');
  const bookingsQuery = useQuery({ queryKey: ['company-bookings'], queryFn: getCompanyBookings });
  const chargersQuery = useQuery({ queryKey: ['company-chargers'], queryFn: getCompanyChargers });
  const dashboardQuery = useQuery({ queryKey: ['company-dashboard'], queryFn: getCompanyDashboard });
  const bookingMutation = useMutation({ mutationFn: ({ id, status }: { id: number; status: CompanyBooking['status'] }) => updateCompanyBooking(id, status), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['company-bookings'] }), client.invalidateQueries({ queryKey: ['company-dashboard'] })]); }, onError: (error: Error) => Alert.alert('Could not update booking', error.message) });
  const chargerMutation = useMutation({ mutationFn: ({ charger, status }: { charger: CompanyCharger; status: CompanyCharger['status'] }) => updateCompanyCharger(charger.id, { stationId: charger.stationId, chargerCode: charger.chargerCode, connectorType: charger.connectorType, powerKw: charger.powerKw, status, maintenanceMode: status === 'MAINTENANCE', firmwareVersion: charger.firmwareVersion, healthScore: charger.healthScore }), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['company-chargers'] }), client.invalidateQueries({ queryKey: ['company-dashboard'] })]); }, onError: (error: Error) => Alert.alert('Could not update charger', error.message) });
  if (bookingsQuery.isLoading || chargersQuery.isLoading || dashboardQuery.isLoading) return <LoadingView message="Loading live operations..." />;
  const bookings = bookingsQuery.data ?? [];
  const chargers = chargersQuery.data ?? [];
  const faults = chargers.filter(charger => charger.status === 'FAULT' || charger.status === 'OFFLINE' || charger.healthScore < 70);
  const live = bookings.filter(booking => booking.status === 'IN_PROGRESS');
  const refreshing = bookingsQuery.isRefetching || chargersQuery.isRefetching || dashboardQuery.isRefetching;
  return <View style={styles.screen}><AppHeader title="Operations" subtitle="Bookings, live sessions and faults" rightIcon="pulse-outline" /><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { void bookingsQuery.refetch(); void chargersQuery.refetch(); void dashboardQuery.refetch(); }} colors={[Colors.blue]} />}>
    <View style={styles.metrics}><Metric icon="calendar-outline" value={bookings.length} label="Bookings" /><Metric icon="flash-outline" value={live.length} label="Live sessions" /><Metric icon="warning-outline" value={faults.length} label="Faults" danger /></View>
    <View style={styles.segment}>{(['BOOKINGS','LIVE','FAULTS'] as Tab[]).map(item => <TouchableOpacity key={item} style={[styles.segmentButton, tab === item && styles.segmentActive]} onPress={() => setTab(item)}><Text style={[styles.segmentText, tab === item && styles.segmentTextActive]}>{item === 'BOOKINGS' ? 'Bookings' : item === 'LIVE' ? 'Live' : 'Faults'}</Text></TouchableOpacity>)}</View>
    {tab === 'BOOKINGS' && <View style={styles.list}>{bookings.map(booking => <BookingRow key={booking.id} booking={booking} onUpdate={status => bookingMutation.mutate({ id: booking.id, status })} />)}{!bookings.length && <Empty icon="calendar-outline" text="Bookings at company stations appear here." />}</View>}
    {tab === 'LIVE' && <View style={styles.list}>{live.map(booking => <BookingRow key={booking.id} booking={booking} onUpdate={status => bookingMutation.mutate({ id: booking.id, status })} />)}{!live.length && <Empty icon="pulse-outline" text="No active charging sessions right now." />}</View>}
    {tab === 'FAULTS' && <View style={styles.list}>{faults.map(charger => <View key={charger.id} style={styles.faultRow}><View style={styles.faultIcon}><Ionicons name="warning-outline" size={19} color={Colors.error} /></View><View style={styles.copy}><Text style={styles.title}>{charger.chargerCode}</Text><Text style={styles.sub}>{charger.stationName} · {charger.status} · {charger.healthScore}% health</Text></View><TouchableOpacity style={styles.action} onPress={() => chargerMutation.mutate({ charger, status: charger.status === 'MAINTENANCE' ? 'ONLINE' : 'MAINTENANCE' })}><Text>{charger.status === 'MAINTENANCE' ? 'Restore' : 'Isolate'}</Text></TouchableOpacity></View>)}{!faults.length && <Empty icon="checkmark-circle-outline" text="No chargers need urgent attention." />}</View>}
  </ScrollView></View>;
}

function BookingRow({ booking, onUpdate }: { booking: CompanyBooking; onUpdate: (status: CompanyBooking['status']) => void }) { const next = booking.status === 'PENDING' ? 'CONFIRMED' : booking.status === 'CONFIRMED' ? 'IN_PROGRESS' : booking.status === 'IN_PROGRESS' ? 'COMPLETED' : null; return <View style={styles.bookingRow}><View style={styles.bookingTop}><View style={styles.bookingIcon}><Ionicons name="calendar-outline" size={18} color={Colors.blue} /></View><View style={styles.copy}><Text style={styles.title}>{booking.stationName}</Text><Text style={styles.sub}>{new Date(booking.startTime).toLocaleString('en-IN')} · {booking.durationHours}h</Text></View><View style={styles.status}><Text style={styles.statusText}>{booking.status}</Text></View></View><View style={styles.bookingMeta}><Text>{booking.kwhDelivered} kWh</Text><Text>{money(booking.totalAmount)}</Text></View>{next || !['COMPLETED','CANCELLED'].includes(booking.status) ? <View style={styles.actions}>{next && <TouchableOpacity style={styles.primaryAction} onPress={() => onUpdate(next)}><Text>{next === 'CONFIRMED' ? 'Approve' : next === 'IN_PROGRESS' ? 'Start session' : 'Complete'}</Text></TouchableOpacity>}{!['COMPLETED','CANCELLED'].includes(booking.status) && <TouchableOpacity style={styles.cancelAction} onPress={() => onUpdate('CANCELLED')}><Text>Cancel</Text></TouchableOpacity>}</View> : null}</View>; }
function Metric({ icon, value, label, danger }: { icon: keyof typeof Ionicons.glyphMap; value: number; label: string; danger?: boolean }) { return <View style={styles.metric}><View style={[styles.metricIcon, danger && styles.metricIconDanger]}><Ionicons name={icon} size={18} color={danger ? Colors.error : Colors.blue} /></View><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Empty({ icon, text }: { icon: keyof typeof Ionicons.glyphMap; text: string }) { return <View style={styles.empty}><Ionicons name={icon} size={27} color={Colors.textMuted} /><Text style={styles.emptyText}>{text}</Text></View>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background }, content: { padding: 16, paddingBottom: 32 }, metrics: { flexDirection: 'row', gap: 8 }, metric: { flex: 1, padding: 11, borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 14, backgroundColor: Colors.white }, metricIcon: { width: 32, height: 32, borderRadius: 9, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blueLight }, metricIconDanger: { backgroundColor: Colors.errorLight }, metricValue: { marginTop: 8, color: Colors.textPrimary, fontSize: 16, fontWeight: '900' }, metricLabel: { marginTop: 2, color: Colors.textSecondary, fontSize: 8.5 }, segment: { marginTop: 13, padding: 4, flexDirection: 'row', borderRadius: 14, backgroundColor: '#E8EBF0' }, segmentButton: { flex: 1, minHeight: 39, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, segmentActive: { backgroundColor: Colors.white }, segmentText: { color: Colors.textSecondary, fontSize: 9.5, fontWeight: '800' }, segmentTextActive: { color: Colors.blue }, list: { marginTop: 11, overflow: 'hidden', borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 17, backgroundColor: Colors.white },
  bookingRow: { padding: 13, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, bookingTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, bookingIcon: { width: 37, height: 37, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blueLight }, copy: { flex: 1 }, title: { color: Colors.textPrimary, fontSize: 11, fontWeight: '800' }, sub: { marginTop: 3, color: Colors.textSecondary, fontSize: 8.5 }, status: { paddingHorizontal: 7, paddingVertical: 4, borderRadius: 8, backgroundColor: Colors.primaryLight }, statusText: { color: Colors.primary, fontSize: 7, fontWeight: '900' }, bookingMeta: { marginTop: 11, flexDirection: 'row', justifyContent: 'space-between' }, actions: { marginTop: 11, flexDirection: 'row', gap: 7 }, primaryAction: { flex: 1, minHeight: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: Colors.blue }, cancelAction: { minWidth: 90, minHeight: 36, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#FECDCA', borderRadius: 9, backgroundColor: '#FFFBFA' },
  faultRow: { minHeight: 68, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, faultIcon: { width: 38, height: 38, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.errorLight }, action: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 9, backgroundColor: Colors.primaryLight }, empty: { minHeight: 150, alignItems: 'center', justifyContent: 'center' }, emptyText: { marginTop: 7, color: Colors.textSecondary, fontSize: 9.5 },
});
