import React, { useState } from 'react';
import { Alert, Modal, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadingView } from '../../src/components/LoadingView';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { Colors } from '../../src/constants/colors';
import { askCompanyAssistant, createCompanyEmployee, deleteCompanyEmployee, downloadCompanyReport, getCompanyActivityLogs, getCompanyAnalytics, getCompanyDashboard, getCompanyEmployees } from '../../src/features/company/company.api';

type Tab = 'ANALYTICS' | 'AI' | 'TEAM' | 'REPORTS';
function money(value: number) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0); }

export default function CompanyInsightsScreen() {
  const client = useQueryClient();
  const [tab, setTab] = useState<Tab>('ANALYTICS');
  const [question, setQuestion] = useState("Show today's revenue");
  const [answer, setAnswer] = useState('Ask about revenue, demand, faults, pricing, energy or expansion.');
  const [showEmployee, setShowEmployee] = useState(false);
  const [employee, setEmployee] = useState({ name: '', email: '', phone: '', role: 'OPERATOR', permissions: 'stations:read,bookings:read' });
  const analytics = useQuery({ queryKey: ['company-analytics'], queryFn: getCompanyAnalytics });
  const dashboard = useQuery({ queryKey: ['company-dashboard'], queryFn: getCompanyDashboard });
  const employees = useQuery({ queryKey: ['company-employees'], queryFn: getCompanyEmployees });
  const activityLogs = useQuery({ queryKey: ['company-activity-logs'], queryFn: getCompanyActivityLogs });
  const aiMutation = useMutation({ mutationFn: askCompanyAssistant, onSuccess: data => setAnswer(data.answer), onError: (error: Error) => Alert.alert('Assistant unavailable', error.message) });
  const employeeMutation = useMutation({ mutationFn: () => createCompanyEmployee({ ...employee, active: true }), onSuccess: async () => { setShowEmployee(false); setEmployee({ name: '', email: '', phone: '', role: 'OPERATOR', permissions: 'stations:read,bookings:read' }); await Promise.all([client.invalidateQueries({ queryKey: ['company-employees'] }), client.invalidateQueries({ queryKey: ['company-activity-logs'] })]); }, onError: (error: Error) => Alert.alert('Could not add employee', error.message) });
  const deleteMutation = useMutation({ mutationFn: deleteCompanyEmployee, onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['company-employees'] }), client.invalidateQueries({ queryKey: ['company-activity-logs'] })]); }, onError: (error: Error) => Alert.alert('Could not remove employee', error.message) });
  const reportMutation = useMutation({ mutationFn: ({ type, format }: { type: 'ANALYTICS' | 'REVENUE'; format: 'PDF' | 'XLSX' }) => downloadCompanyReport(type, format), onSuccess: data => Alert.alert('Report generated', `${Math.ceil(data.byteLength / 1024)} KB is ready. Use the web dashboard to download or email this company report.`), onError: (error: Error) => Alert.alert('Could not generate report', error.message) });
  if (analytics.isLoading || dashboard.isLoading || employees.isLoading || activityLogs.isLoading) return <LoadingView message="Preparing company insights..." />;
  return <View style={styles.screen}><AppHeader title="Insights" subtitle="Analytics, AI, team and reports" rightIcon="sparkles-outline" /><ScrollView contentContainerStyle={styles.content}>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.segment}>{(['ANALYTICS','AI','TEAM','REPORTS'] as Tab[]).map(item => <TouchableOpacity key={item} style={[styles.segmentButton, tab === item && styles.segmentActive]} onPress={() => setTab(item)}><Text style={[styles.segmentText, tab === item && styles.segmentTextActive]}>{item === 'TEAM' ? 'Employees' : item}</Text></TouchableOpacity>)}</ScrollView>
    {tab === 'ANALYTICS' && <><View style={styles.metrics}><Metric label="Today" value={money(analytics.data?.dailyRevenue ?? 0)} /><Metric label="This week" value={money(analytics.data?.weeklyRevenue ?? 0)} /><Metric label="This month" value={money(analytics.data?.monthlyRevenue ?? 0)} /><Metric label="Growth" value={`${analytics.data?.customerGrowthPercent ?? 0}%`} /></View><View style={styles.card}><Header icon="trophy-outline" title="Top performing stations" sub="Completed-session revenue" />{(analytics.data?.topStations ?? []).map((station, index) => <View key={station.station} style={styles.rankRow}><Text style={styles.rank}>#{index + 1}</Text><Text style={styles.rankName}>{station.station}</Text><Text style={styles.rankValue}>{money(station.revenue)}</Text></View>)}{!analytics.data?.topStations.length && <Empty text="Complete charging sessions to populate analytics." />}</View><View style={styles.card}><Header icon="pulse-outline" title="Demand intelligence" sub="Actual company-scoped performance" /><View style={styles.insightGrid}><Insight label="Peak usage" value={analytics.data?.peakUsageHour ?? '18:00'} /><Insight label="Sessions" value={analytics.data?.successfulSessions ?? 0} /><Insight label="Energy" value={`${dashboard.data?.energyDeliveredKwh ?? 0} kWh`} /><Insight label="Utilization" value={`${dashboard.data?.utilizationRate ?? 0}%`} /></View></View></>}
    {tab === 'AI' && <View style={[styles.card, styles.aiCard]}><View style={styles.aiOrb}><Ionicons name="sparkles" size={26} color={Colors.white} /></View><Text style={styles.aiKicker}>VIDYUT AI</Text><Text style={styles.aiTitle}>Ask your network</Text><Text style={styles.aiSub}>Answers use only this company's live stations, chargers, sessions and revenue.</Text><View style={styles.answer}><Ionicons name="analytics-outline" size={22} color={Colors.blue} /><Text style={styles.answerText}>{answer}</Text></View><View style={styles.askRow}><TextInput value={question} onChangeText={setQuestion} style={styles.askInput} placeholder="Ask a company question" placeholderTextColor={Colors.textMuted} /><TouchableOpacity style={styles.send} onPress={() => aiMutation.mutate(question)}><Ionicons name="send" size={17} color={Colors.white} /></TouchableOpacity></View><View style={styles.prompts}>{["Show today's revenue",'Which chargers need maintenance?','When is peak demand?','Where should we expand?'].map(item => <TouchableOpacity key={item} style={styles.prompt} onPress={() => setQuestion(item)}><Text>{item}</Text></TouchableOpacity>)}</View></View>}
    {tab === 'TEAM' && <><View style={styles.card}><Header icon="people-outline" title="Employees & roles" sub="Managers, operators, maintenance and finance" action="Add" onAction={() => setShowEmployee(true)} />{(employees.data ?? []).map(item => <View key={item.id} style={styles.employeeRow}><View style={styles.avatar}><Text>{item.name.split(' ').map(part => part[0]).slice(0,2).join('')}</Text></View><View style={styles.employeeCopy}><Text style={styles.employeeName}>{item.name}</Text><Text style={styles.employeeMeta}>{item.role} · {item.email}</Text><Text style={styles.permissions}>{item.permissions || 'Default permissions'}</Text></View><TouchableOpacity onPress={() => Alert.alert('Remove employee?', item.email, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: () => deleteMutation.mutate(item.id) }])}><Ionicons name="trash-outline" size={17} color={Colors.error} /></TouchableOpacity></View>)}{!employees.data?.length && <Empty text="Add employees and assign least-privilege roles." />}</View><View style={styles.card}><Header icon="time-outline" title="Activity logs" sub="Latest protected company changes" />{(activityLogs.data ?? []).slice(0, 20).map(item => <View key={item.id} style={styles.activityRow}><View style={styles.activityIcon}><Ionicons name="shield-checkmark-outline" size={16} color={Colors.primary} /></View><View style={styles.employeeCopy}><Text style={styles.employeeName}>{item.description}</Text><Text style={styles.employeeMeta}>{item.action} · {item.resourceType} · {new Date(item.createdAt).toLocaleString()}</Text></View></View>)}{!activityLogs.data?.length && <Empty text="Protected changes will be recorded here." />}</View></>}
    {tab === 'REPORTS' && <View style={styles.card}><Header icon="document-text-outline" title="Reports & exports" sub="Real PDF and Excel files from company data" /><Report icon="analytics-outline" title="Network analytics" text="Utilization, station ranking, customer growth and energy." onPdf={() => reportMutation.mutate({ type: 'ANALYTICS', format: 'PDF' })} onExcel={() => reportMutation.mutate({ type: 'ANALYTICS', format: 'XLSX' })} /><Report icon="cash-outline" title="Revenue report" text="Daily, weekly and monthly revenue for reconciliation." onPdf={() => reportMutation.mutate({ type: 'REVENUE', format: 'PDF' })} onExcel={() => reportMutation.mutate({ type: 'REVENUE', format: 'XLSX' })} /></View>}
  </ScrollView><EmployeeModal visible={showEmployee} employee={employee} setEmployee={setEmployee} saving={employeeMutation.isPending} onClose={() => setShowEmployee(false)} onSave={() => employeeMutation.mutate()} /></View>;
}

function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Header({ icon, title, sub, action, onAction }: { icon: keyof typeof Ionicons.glyphMap; title: string; sub: string; action?: string; onAction?: () => void }) { return <View style={styles.cardHead}><View style={styles.headIcon}><Ionicons name={icon} size={18} color={Colors.blue} /></View><View style={styles.headCopy}><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardSub}>{sub}</Text></View>{action && <TouchableOpacity style={styles.headAction} onPress={onAction}><Text>{action}</Text></TouchableOpacity>}</View>; }
function Insight({ label, value }: { label: string; value: string | number }) { return <View style={styles.insight}><Text style={styles.insightLabel}>{label}</Text><Text style={styles.insightValue}>{value}</Text></View>; }
function Empty({ text }: { text: string }) { return <View style={styles.empty}><Ionicons name="file-tray-outline" size={24} color={Colors.textMuted} /><Text style={styles.emptyText}>{text}</Text></View>; }
function Report({ icon, title, text, onPdf, onExcel }: { icon: keyof typeof Ionicons.glyphMap; title: string; text: string; onPdf: () => void; onExcel: () => void }) { return <View style={styles.report}><View style={styles.reportIcon}><Ionicons name={icon} size={20} color={Colors.primary} /></View><View style={styles.reportCopy}><Text style={styles.reportTitle}>{title}</Text><Text style={styles.reportText}>{text}</Text><View style={styles.reportActions}><TouchableOpacity onPress={onPdf}><Text>PDF</Text></TouchableOpacity><TouchableOpacity onPress={onExcel}><Text>Excel</Text></TouchableOpacity></View></View></View>; }
function EmployeeModal({ visible, employee, setEmployee, saving, onClose, onSave }: { visible: boolean; employee: { name: string; email: string; phone: string; role: string; permissions: string }; setEmployee: React.Dispatch<React.SetStateAction<{ name: string; email: string; phone: string; role: string; permissions: string }>>; saving: boolean; onClose: () => void; onSave: () => void }) { const field = (key: keyof typeof employee, label: string) => <View><Text style={styles.fieldLabel}>{label}</Text><TextInput value={employee[key]} onChangeText={value => setEmployee(current => ({ ...current, [key]: value }))} style={styles.input} placeholderTextColor={Colors.textMuted} /></View>; return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.modalTitle}>Add company employee</Text>{field('name','Full name')}{field('email','Work email')}{field('phone','Phone')}{field('permissions','Permissions')}<Text style={styles.fieldLabel}>Role</Text><View style={styles.roleRow}>{['MANAGER','OPERATOR','MAINTENANCE','FINANCE'].map(role => <TouchableOpacity key={role} style={[styles.roleChip, employee.role === role && styles.roleActive]} onPress={() => setEmployee(current => ({ ...current, role }))}><Text>{role}</Text></TouchableOpacity>)}</View><View style={styles.modalActions}><PrimaryButton title="Cancel" variant="outline" onPress={onClose} style={styles.modalButton} /><PrimaryButton title="Add employee" onPress={onSave} loading={saving} style={styles.modalButton} /></View></View></View></Modal>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background }, content: { padding: 16, paddingBottom: 32 }, segment: { gap: 7, paddingBottom: 4 }, segmentButton: { minWidth: 92, paddingHorizontal: 13, paddingVertical: 9, borderWidth: 1, borderColor: Colors.border, borderRadius: 10, backgroundColor: Colors.white }, segmentActive: { borderColor: Colors.blue, backgroundColor: Colors.blue }, segmentText: { color: Colors.textSecondary, fontSize: 9, fontWeight: '800', textAlign: 'center' }, segmentTextActive: { color: Colors.white }, metrics: { marginTop: 11, flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, metric: { width: '47%', flexGrow: 1, padding: 14, borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 14, backgroundColor: Colors.white }, metricValue: { color: Colors.textPrimary, fontSize: 17, fontWeight: '900' }, metricLabel: { marginTop: 3, color: Colors.textSecondary, fontSize: 8.5 }, card: { marginTop: 12, overflow: 'hidden', borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 18, backgroundColor: Colors.white }, cardHead: { padding: 14, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, headIcon: { width: 36, height: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blueLight }, headCopy: { flex: 1 }, cardTitle: { color: Colors.textPrimary, fontSize: 12.5, fontWeight: '900' }, cardSub: { marginTop: 3, color: Colors.textSecondary, fontSize: 8.5 }, headAction: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 8, backgroundColor: Colors.blueLight }, rankRow: { minHeight: 50, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, rank: { width: 30, color: Colors.blue, fontSize: 9, fontWeight: '900' }, rankName: { flex: 1, color: Colors.textPrimary, fontSize: 10.5, fontWeight: '700' }, rankValue: { color: Colors.primary, fontSize: 10, fontWeight: '900' }, insightGrid: { padding: 14, flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, insight: { width: '47%', flexGrow: 1, padding: 12, borderRadius: 11, backgroundColor: Colors.background }, insightLabel: { color: Colors.textSecondary, fontSize: 8.5 }, insightValue: { marginTop: 4, color: Colors.textPrimary, fontSize: 12, fontWeight: '900' },
  aiCard: { padding: 18 }, aiOrb: { width: 52, height: 52, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blue }, aiKicker: { marginTop: 13, color: Colors.blue, fontSize: 8, fontWeight: '900', letterSpacing: 1 }, aiTitle: { marginTop: 4, color: Colors.textPrimary, fontSize: 20, fontWeight: '900' }, aiSub: { marginTop: 4, color: Colors.textSecondary, fontSize: 9.5, lineHeight: 14 }, answer: { marginTop: 17, padding: 14, flexDirection: 'row', alignItems: 'flex-start', gap: 9, borderRadius: 13, backgroundColor: Colors.blueLight }, answerText: { flex: 1, color: Colors.textPrimary, fontSize: 10.5, fontWeight: '700', lineHeight: 15 }, askRow: { marginTop: 13, flexDirection: 'row', gap: 7 }, askInput: { flex: 1, height: 43, paddingHorizontal: 12, borderWidth: 1, borderColor: Colors.border, borderRadius: 11, color: Colors.textPrimary, fontSize: 10.5 }, send: { width: 43, alignItems: 'center', justifyContent: 'center', borderRadius: 11, backgroundColor: Colors.blue }, prompts: { marginTop: 9, flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, prompt: { paddingHorizontal: 8, paddingVertical: 6, borderWidth: 1, borderColor: Colors.border, borderRadius: 99 },
  employeeRow: { minHeight: 68, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, avatar: { width: 39, height: 39, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primaryLight }, employeeCopy: { flex: 1 }, employeeName: { color: Colors.textPrimary, fontSize: 10.5, fontWeight: '800' }, employeeMeta: { marginTop: 2, color: Colors.textSecondary, fontSize: 8.5 }, permissions: { marginTop: 3, color: Colors.blue, fontSize: 7.8 }, empty: { minHeight: 130, alignItems: 'center', justifyContent: 'center' }, emptyText: { marginTop: 6, color: Colors.textSecondary, fontSize: 9.5 }, report: { padding: 14, flexDirection: 'row', gap: 10, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, reportIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primaryLight }, reportCopy: { flex: 1 }, reportTitle: { color: Colors.textPrimary, fontSize: 11, fontWeight: '800' }, reportText: { marginTop: 3, color: Colors.textSecondary, fontSize: 8.5, lineHeight: 12 }, reportActions: { marginTop: 9, flexDirection: 'row', gap: 7 },
  activityRow: { minHeight: 58, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9, borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, activityIcon: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.primaryLight },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16,24,40,.48)' }, modalCard: { padding: 19, paddingBottom: 28, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: Colors.white }, modalTitle: { color: Colors.textPrimary, fontSize: 18, fontWeight: '900' }, fieldLabel: { marginTop: 13, marginBottom: 6, color: Colors.textPrimary, fontSize: 9.5, fontWeight: '800' }, input: { height: 43, paddingHorizontal: 12, borderWidth: 1, borderColor: Colors.border, borderRadius: 11, color: Colors.textPrimary, fontSize: 11 }, roleRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, roleChip: { paddingHorizontal: 8, paddingVertical: 7, borderWidth: 1, borderColor: Colors.border, borderRadius: 8 }, roleActive: { borderColor: Colors.blue, backgroundColor: Colors.blueLight }, modalActions: { marginTop: 21, flexDirection: 'row', gap: 8 }, modalButton: { flex: 1 },
});
