import React, { useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadingView } from '../../src/components/LoadingView';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { Colors } from '../../src/constants/colors';
import { confirmCompanyEmail, getCompanyNotifications, getCompanyProfile, requestCompanyEmailCode, submitCompanyVerification, updateCompanyProfile, updateCompanySettings } from '../../src/features/company/company.api';
import { useAuthStore } from '../../src/features/auth/auth.store';

export default function CompanyProfileScreen() {
  const router = useRouter();
  const client = useQueryClient();
  const logout = useAuthStore(state => state.logout);
  const profileQuery = useQuery({ queryKey: ['company-profile'], queryFn: getCompanyProfile });
  const notifications = useQuery({ queryKey: ['company-notifications'], queryFn: getCompanyNotifications });
  const [profileForm, setProfileForm] = useState({ companyName: '', contactName: '', supportEmail: '', supportPhone: '', businessAddress: '', website: '' });
  const [verificationForm, setVerificationForm] = useState({ gstNumber: '', kycDocumentUrl: '', businessAddress: '' });
  const [code, setCode] = useState('');
  useEffect(() => { const data = profileQuery.data; if (data) { setProfileForm({ companyName: data.companyName, contactName: data.contactName, supportEmail: data.supportEmail ?? '', supportPhone: data.supportPhone ?? '', businessAddress: data.businessAddress ?? '', website: data.website ?? '' }); setVerificationForm({ gstNumber: data.gstNumber ?? '', kycDocumentUrl: data.kycDocumentUrl ?? '', businessAddress: data.businessAddress ?? '' }); } }, [profileQuery.data]);
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: ['company-profile'] }), client.invalidateQueries({ queryKey: ['company-notifications'] })]); };
  const profileMutation = useMutation({ mutationFn: () => updateCompanyProfile(profileForm), onSuccess: async () => { await refresh(); Alert.alert('Profile saved'); }, onError: (error: Error) => Alert.alert('Could not save', error.message) });
  const kycMutation = useMutation({ mutationFn: () => submitCompanyVerification(verificationForm), onSuccess: async () => { await refresh(); Alert.alert('Verification submitted', 'An admin can now approve the GST/KYC review.'); }, onError: (error: Error) => Alert.alert('Could not submit', error.message) });
  const codeMutation = useMutation({ mutationFn: requestCompanyEmailCode, onSuccess: async message => { await refresh(); Alert.alert('Code sent', message); }, onError: (error: Error) => Alert.alert('Could not send code', error.message) });
  const confirmMutation = useMutation({ mutationFn: () => confirmCompanyEmail(code), onSuccess: async () => { await refresh(); setCode(''); Alert.alert('Email verified'); }, onError: (error: Error) => Alert.alert('Code not accepted', error.message) });
  const settingsMutation = useMutation({ mutationFn: (next: { emailNotifications: boolean; pushNotifications: boolean; timezone: string }) => updateCompanySettings(next), onSuccess: refresh, onError: (error: Error) => Alert.alert('Could not update settings', error.message) });
  if (profileQuery.isLoading) return <LoadingView message="Loading company profile..." />;
  const profile = profileQuery.data;
  const verificationNotification = notifications.data?.find(item => item.title.includes('email verification'));
  const signOut = () => Alert.alert('Sign out', 'Sign out of this protected company workspace?', [{ text: 'Cancel', style: 'cancel' }, { text: 'Sign out', style: 'destructive', onPress: async () => { await logout(); router.replace('/(auth)/login'); } }]);
  return <View style={styles.screen}><AppHeader title="Company profile" subtitle="Identity, verification and settings" rightIcon="shield-checkmark-outline" /><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.companyCard}><View style={styles.companyIcon}><Ionicons name="business" size={28} color={Colors.blue} /></View><Text style={styles.companyName}>{profile?.companyName}</Text><Text style={styles.companyNumber}>{profile?.registrationNumber}</Text><View style={styles.badges}><Badge label={profile?.emailVerified ? 'EMAIL VERIFIED' : 'EMAIL PENDING'} verified={profile?.emailVerified} /><Badge label={`KYC ${profile?.verificationStatus}`} verified={profile?.verificationStatus === 'VERIFIED'} /></View></View>

    {!profile?.emailVerified && <Section title="Email verification" icon="mail-outline"><Text style={styles.help}>Request a one-time code. In this development build the delivery is also mirrored to the company notification inbox.</Text><PrimaryButton title={codeMutation.isPending ? 'Sending...' : 'Send verification code'} variant="outline" onPress={() => codeMutation.mutate()} loading={codeMutation.isPending} /><Text style={styles.latest}>{verificationNotification?.message ?? 'No active code requested.'}</Text><View style={styles.codeRow}><TextInput value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="6-digit code" placeholderTextColor={Colors.textMuted} style={styles.codeInput} /><TouchableOpacity style={styles.confirm} onPress={() => confirmMutation.mutate()}><Text>Verify</Text></TouchableOpacity></View></Section>}

    <Section title="Organization profile" icon="business-outline"><Field label="Company name" value={profileForm.companyName} onChangeText={companyName => setProfileForm(current => ({ ...current, companyName }))} /><Field label="Primary contact" value={profileForm.contactName} onChangeText={contactName => setProfileForm(current => ({ ...current, contactName }))} /><Field label="Support email" value={profileForm.supportEmail} onChangeText={supportEmail => setProfileForm(current => ({ ...current, supportEmail }))} /><Field label="Support phone" value={profileForm.supportPhone} onChangeText={supportPhone => setProfileForm(current => ({ ...current, supportPhone }))} /><Field label="Business address" value={profileForm.businessAddress} onChangeText={businessAddress => setProfileForm(current => ({ ...current, businessAddress }))} /><Field label="Website" value={profileForm.website} onChangeText={website => setProfileForm(current => ({ ...current, website }))} /><PrimaryButton title="Save company profile" onPress={() => profileMutation.mutate()} loading={profileMutation.isPending} style={styles.saveButton} /></Section>

    <Section title="GST & business KYC" icon="document-text-outline"><Text style={styles.help}>Operational changes unlock only after email verification and admin approval of these documents.</Text><Field label="GST number" value={verificationForm.gstNumber} autoCapitalize="characters" onChangeText={gstNumber => setVerificationForm(current => ({ ...current, gstNumber: gstNumber.toUpperCase() }))} /><Field label="KYC document URL" value={verificationForm.kycDocumentUrl} onChangeText={kycDocumentUrl => setVerificationForm(current => ({ ...current, kycDocumentUrl }))} /><Field label="Registered business address" value={verificationForm.businessAddress} onChangeText={businessAddress => setVerificationForm(current => ({ ...current, businessAddress }))} /><PrimaryButton title="Submit for verification" onPress={() => kycMutation.mutate()} loading={kycMutation.isPending} style={styles.saveButton} /></Section>

    <Section title="Company settings" icon="settings-outline"><Setting label="Email reports & alerts" value={profile?.emailNotifications ?? true} onChange={emailNotifications => settingsMutation.mutate({ emailNotifications, pushNotifications: profile?.pushNotifications ?? true, timezone: profile?.timezone ?? 'Asia/Kolkata' })} /><Setting label="Push notifications" value={profile?.pushNotifications ?? true} onChange={pushNotifications => settingsMutation.mutate({ emailNotifications: profile?.emailNotifications ?? true, pushNotifications, timezone: profile?.timezone ?? 'Asia/Kolkata' })} /><View style={styles.timezone}><Text style={styles.settingLabel}>Timezone</Text><Text style={styles.timezoneValue}>{profile?.timezone ?? 'Asia/Kolkata'}</Text></View></Section>

    <View style={styles.isolation}><Ionicons name="lock-closed-outline" size={18} color={Colors.blue} /><Text style={styles.isolationText}>Company accounts cannot enter EV Owner or Host workspaces. Backend role and ownership checks enforce this partition.</Text></View><TouchableOpacity style={styles.logout} onPress={signOut}><Ionicons name="log-out-outline" size={18} color={Colors.error} /><Text style={styles.logoutText}>Sign out</Text></TouchableOpacity>
  </ScrollView></View>;
}

function Badge({ label, verified }: { label: string; verified?: boolean }) { return <View style={[styles.badge, verified && styles.badgeVerified]}><Text style={[styles.badgeText, verified && styles.badgeTextVerified]}>{label}</Text></View>; }
function Section({ title, icon, children }: { title: string; icon: keyof typeof Ionicons.glyphMap; children: React.ReactNode }) { return <View style={styles.section}><View style={styles.sectionHead}><View style={styles.sectionIcon}><Ionicons name={icon} size={18} color={Colors.blue} /></View><Text style={styles.sectionTitle}>{title}</Text></View>{children}</View>; }
function Field(props: React.ComponentProps<typeof TextInput> & { label: string }) { const { label, ...inputProps } = props; return <View><Text style={styles.fieldLabel}>{label}</Text><TextInput {...inputProps} style={styles.input} placeholderTextColor={Colors.textMuted} /></View>; }
function Setting({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <View style={styles.setting}><Text style={styles.settingLabel}>{label}</Text><Switch value={value} onValueChange={onChange} trackColor={{ false: Colors.border, true: '#93C5FD' }} thumbColor={value ? Colors.blue : Colors.white} /></View>; }

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background }, content: { padding: 16, paddingBottom: 32 }, companyCard: { padding: 20, alignItems: 'center', borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 19, backgroundColor: Colors.white }, companyIcon: { width: 64, height: 64, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blueLight }, companyName: { marginTop: 12, color: Colors.textPrimary, fontSize: 17, fontWeight: '900' }, companyNumber: { marginTop: 3, color: Colors.textSecondary, fontSize: 9.5 }, badges: { marginTop: 11, flexDirection: 'row', gap: 6 }, badge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, backgroundColor: Colors.warningLight }, badgeVerified: { backgroundColor: Colors.primaryLight }, badgeText: { color: Colors.warning, fontSize: 7.5, fontWeight: '900' }, badgeTextVerified: { color: Colors.primary },
  section: { marginTop: 13, padding: 16, borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 18, backgroundColor: Colors.white }, sectionHead: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 3 }, sectionIcon: { width: 34, height: 34, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blueLight }, sectionTitle: { color: Colors.textPrimary, fontSize: 13, fontWeight: '900' }, help: { marginTop: 8, color: Colors.textSecondary, fontSize: 9, lineHeight: 14 }, latest: { marginTop: 10, padding: 9, color: Colors.textSecondary, fontSize: 8.5, borderRadius: 9, backgroundColor: Colors.background }, codeRow: { marginTop: 8, flexDirection: 'row', gap: 7 }, codeInput: { flex: 1, height: 42, paddingHorizontal: 12, borderWidth: 1, borderColor: Colors.border, borderRadius: 10, color: Colors.textPrimary, fontSize: 11, letterSpacing: 2 }, confirm: { minWidth: 80, alignItems: 'center', justifyContent: 'center', borderRadius: 10, backgroundColor: Colors.blue },
  fieldLabel: { marginTop: 12, marginBottom: 5, color: Colors.textPrimary, fontSize: 9.5, fontWeight: '800' }, input: { height: 42, paddingHorizontal: 11, borderWidth: 1, borderColor: Colors.border, borderRadius: 10, color: Colors.textPrimary, fontSize: 10.5, backgroundColor: Colors.background }, saveButton: { marginTop: 16 }, setting: { minHeight: 49, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: Colors.borderSoft }, settingLabel: { color: Colors.textPrimary, fontSize: 10.5, fontWeight: '700' }, timezone: { minHeight: 49, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, timezoneValue: { color: Colors.blue, fontSize: 9.5, fontWeight: '800' }, isolation: { marginTop: 14, padding: 13, flexDirection: 'row', gap: 9, borderRadius: 14, backgroundColor: Colors.blueLight }, isolationText: { flex: 1, color: Colors.textSecondary, fontSize: 9.5, lineHeight: 14 }, logout: { minHeight: 49, marginTop: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#FECDCA', borderRadius: 13, backgroundColor: '#FFFBFA' }, logoutText: { color: Colors.error, fontSize: 11, fontWeight: '800' },
});
