import React, { useState } from 'react';
import { Alert, Modal, RefreshControl, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadingView } from '../../src/components/LoadingView';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { Colors } from '../../src/constants/colors';
import {
  createCompanyCharger, createCompanyStation, deleteCompanyStation, getCompanyChargers,
  getCompanyStations, updateCompanyCharger, updateCompanyPricing, updateCompanyStation,
} from '../../src/features/company/company.api';
import { CompanyCharger, CompanyStation } from '../../src/features/company/company.types';

type Segment = 'STATIONS' | 'CHARGERS' | 'PRICING';
type Editor = 'station' | 'charger' | 'pricing' | null;

export default function CompanyNetworkScreen() {
  const queryClient = useQueryClient();
  const [segment, setSegment] = useState<Segment>('STATIONS');
  const [search, setSearch] = useState('');
  const [editor, setEditor] = useState<Editor>(null);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState<Record<string, string | boolean>>({});
  const stationsQuery = useQuery({ queryKey: ['company-stations'], queryFn: getCompanyStations });
  const chargersQuery = useQuery({ queryKey: ['company-chargers'], queryFn: getCompanyChargers });
  const stations = stationsQuery.data ?? [];
  const chargers = chargersQuery.data ?? [];

  const saveMutation = useMutation({
    mutationFn: async () => {
      if (editor === 'station') {
        const body = { ...form, latitude: Number(form.latitude), longitude: Number(form.longitude), pricePerKwh: Number(form.pricePerKwh), powerKw: Number(form.powerKw), connectorType: form.connectorType || 'CCS2' };
        return editingId ? updateCompanyStation(editingId, body) : createCompanyStation(body);
      }
      if (editor === 'charger') {
        const body = { ...form, stationId: Number(form.stationId), powerKw: Number(form.powerKw), healthScore: Number(form.healthScore), maintenanceMode: Boolean(form.maintenanceMode) };
        return editingId ? updateCompanyCharger(editingId, body) : createCompanyCharger(body);
      }
      const body = { ...form, pricePerKwh: Number(form.pricePerKwh), timeBasedPricePerHour: Number(form.timeBasedPricePerHour), peakPricePerKwh: Number(form.peakPricePerKwh), studentDiscountPercent: Number(form.studentDiscountPercent), corporatePricePerKwh: Number(form.corporatePricePerKwh), couponDiscountPercent: Number(form.couponDiscountPercent), dynamicPricingEnabled: Boolean(form.dynamicPricingEnabled) };
      return updateCompanyPricing(editingId!, body);
    },
    onSuccess: async () => { setEditor(null); await Promise.all([queryClient.invalidateQueries({ queryKey: ['company-stations'] }), queryClient.invalidateQueries({ queryKey: ['company-chargers'] }), queryClient.invalidateQueries({ queryKey: ['company-dashboard'] })]); Alert.alert('Saved', 'Company network changes are live.'); },
    onError: (error: Error) => Alert.alert('Could not save', error.message),
  });

  const deleteMutation = useMutation({ mutationFn: deleteCompanyStation, onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['company-stations'] }); }, onError: (error: Error) => Alert.alert('Could not delete', error.message) });

  const openStation = (station?: CompanyStation) => {
    setEditingId(station?.id ?? null); setEditor('station');
    setForm(station ? { name: station.name, address: station.address, city: station.city, latitude: String(station.latitude), longitude: String(station.longitude), pricePerKwh: String(station.pricePerKwh), amenities: station.amenities ?? '', workingHours: station.workingHours ?? '', imageUrl: station.imageUrl ?? '' } : { name: '', address: '', city: '', latitude: '26.8467', longitude: '80.9462', pricePerKwh: '18', powerKw: '60', connectorType: 'CCS2', amenities: 'Parking, Restroom', workingHours: 'Open 24 hours', imageUrl: '' });
  };
  const openCharger = (charger?: CompanyCharger) => {
    if (!stations.length) { Alert.alert('Add a station first', 'Every charger must belong to a verified company station.'); return; }
    setEditingId(charger?.id ?? null); setEditor('charger');
    setForm(charger ? { stationId: String(charger.stationId), chargerCode: charger.chargerCode, connectorType: charger.connectorType, powerKw: String(charger.powerKw), status: charger.status, firmwareVersion: charger.firmwareVersion, healthScore: String(charger.healthScore), maintenanceMode: charger.maintenanceMode } : { stationId: String(stations[0].id), chargerCode: '', connectorType: 'CCS2', powerKw: '60', status: 'ONLINE', firmwareVersion: '1.0.0', healthScore: '100', maintenanceMode: false });
  };
  const openPricing = (station: CompanyStation) => {
    setEditingId(station.id); setEditor('pricing'); setForm({ pricePerKwh: String(station.pricePerKwh), timeBasedPricePerHour: '0', peakPricePerKwh: String(station.peakPricePerKwh ?? station.pricePerKwh), peakHours: station.peakHours ?? '18:00-22:00', studentDiscountPercent: String(station.studentDiscountPercent ?? 10), corporatePricePerKwh: String(station.corporatePricePerKwh ?? station.pricePerKwh), couponCode: station.couponCode ?? '', couponDiscountPercent: String(station.couponDiscountPercent ?? 0), dynamicPricingEnabled: station.dynamicPricingEnabled });
  };

  if (stationsQuery.isLoading || chargersQuery.isLoading) return <LoadingView message="Loading company network..." />;
  const visibleStations = stations.filter(item => `${item.name} ${item.city}`.toLowerCase().includes(search.toLowerCase()));
  const visibleChargers = chargers.filter(item => `${item.chargerCode} ${item.stationName}`.toLowerCase().includes(search.toLowerCase()));
  const refreshing = stationsQuery.isRefetching || chargersQuery.isRefetching;
  return (
    <View style={styles.screen}>
      <AppHeader title="Company network" subtitle="Stations, chargers and pricing" rightIcon="add" onRightPress={() => segment === 'CHARGERS' ? openCharger() : openStation()} />
      <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { void stationsQuery.refetch(); void chargersQuery.refetch(); }} colors={[Colors.blue]} />}>
        <View style={styles.segment}>{(['STATIONS','CHARGERS','PRICING'] as Segment[]).map(item => <TouchableOpacity key={item} style={[styles.segmentButton, segment === item && styles.segmentActive]} onPress={() => setSegment(item)}><Text style={[styles.segmentText, segment === item && styles.segmentTextActive]}>{item === 'STATIONS' ? 'Stations' : item === 'CHARGERS' ? 'Chargers' : 'Pricing'}</Text></TouchableOpacity>)}</View>
        <View style={styles.search}><Ionicons name="search" size={17} color={Colors.textMuted} /><TextInput value={search} onChangeText={setSearch} style={styles.searchInput} placeholder="Search network" placeholderTextColor={Colors.textMuted} /></View>
        {segment === 'STATIONS' && <>{visibleStations.map(station => <StationCard key={station.id} station={station} onEdit={() => openStation(station)} onDelete={() => Alert.alert('Delete station?', 'Chargers at this station will also be removed.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => deleteMutation.mutate(station.id) }])} />)}{!visibleStations.length && <Empty icon="business-outline" title="No stations yet" text="Add your first verified charging location." onPress={() => openStation()} />}</>}
        {segment === 'CHARGERS' && <>{visibleChargers.map(charger => <ChargerCard key={charger.id} charger={charger} onEdit={() => openCharger(charger)} />)}{!visibleChargers.length && <Empty icon="flash-outline" title="No chargers yet" text="Provision a charger inside one of your stations." onPress={() => openCharger()} />}</>}
        {segment === 'PRICING' && <>{visibleStations.map(station => <TouchableOpacity key={station.id} style={styles.pricingCard} onPress={() => openPricing(station)}><View style={styles.pricingTop}><View><Text style={styles.stationName}>{station.name}</Text><Text style={styles.stationMeta}>{station.city} · {station.dynamicPricingEnabled ? 'Dynamic pricing' : 'Fixed pricing'}</Text></View><Text style={styles.price}>₹{station.pricePerKwh}/kWh</Text></View><View style={styles.pricingRow}><Price label="Peak" value={`₹${station.peakPricePerKwh ?? station.pricePerKwh}`} /><Price label="Student" value={`${station.studentDiscountPercent ?? 0}% off`} /><Price label="Corporate" value={`₹${station.corporatePricePerKwh ?? station.pricePerKwh}`} /></View><Text style={styles.editHint}>Tap to edit peak, time-based, corporate, student and coupon pricing</Text></TouchableOpacity>)}</>}
      </ScrollView>
      <EditorModal kind={editor} form={form} setForm={setForm} stations={stations} editing={Boolean(editingId)} saving={saveMutation.isPending} onClose={() => setEditor(null)} onSave={() => saveMutation.mutate()} />
    </View>
  );
}

function StationCard({ station, onEdit, onDelete }: { station: CompanyStation; onEdit: () => void; onDelete: () => void }) { return <View style={styles.card}><View style={styles.cardIcon}><Ionicons name="business-outline" size={21} color={Colors.blue} /></View><View style={styles.cardCopy}><View style={styles.nameRow}><Text style={styles.stationName}>{station.name}</Text><Status value={station.status} /></View><Text style={styles.stationMeta}>{station.city} · {station.connectors?.length ?? 0} chargers · {station.workingHours || 'Hours not set'}</Text><Text style={styles.stationSub}>{station.amenities || 'No amenities'} · ₹{station.pricePerKwh}/kWh</Text><View style={styles.cardActions}><TouchableOpacity onPress={onEdit}><Ionicons name="create-outline" size={14} color={Colors.blue} /><Text>Edit</Text></TouchableOpacity><TouchableOpacity onPress={onDelete}><Ionicons name="trash-outline" size={14} color={Colors.error} /><Text style={styles.deleteText}>Delete</Text></TouchableOpacity></View></View></View>; }
function ChargerCard({ charger, onEdit }: { charger: CompanyCharger; onEdit: () => void }) { return <TouchableOpacity style={styles.card} onPress={onEdit}><View style={[styles.cardIcon, charger.status === 'FAULT' && styles.cardIconDanger]}><Ionicons name="flash-outline" size={21} color={charger.status === 'FAULT' ? Colors.error : Colors.primary} /></View><View style={styles.cardCopy}><View style={styles.nameRow}><Text style={styles.stationName}>{charger.chargerCode}</Text><Status value={charger.status} /></View><Text style={styles.stationMeta}>{charger.stationName} · {charger.connectorType} · {charger.powerKw} kW</Text><View style={styles.healthRow}><Text style={styles.stationSub}>Firmware {charger.firmwareVersion}</Text><Text style={[styles.health, charger.healthScore < 70 && { color: Colors.error }]}>{charger.healthScore}% health</Text></View></View><Ionicons name="chevron-forward" size={17} color={Colors.textMuted} /></TouchableOpacity>; }
function Status({ value }: { value: string }) { const danger = value === 'FAULT' || value === 'OFFLINE'; return <View style={[styles.status, danger && styles.statusDanger]}><Text style={[styles.statusText, danger && styles.statusTextDanger]}>{value}</Text></View>; }
function Price({ label, value }: { label: string; value: string }) { return <View><Text style={styles.priceLabel}>{label}</Text><Text style={styles.priceValue}>{value}</Text></View>; }
function Empty({ icon, title, text, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; text: string; onPress: () => void }) { return <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name={icon} size={27} color={Colors.blue} /></View><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{text}</Text><PrimaryButton title="Add now" onPress={onPress} style={styles.emptyButton} /></View>; }

function EditorModal({ kind, form, setForm, stations, editing, saving, onClose, onSave }: { kind: Editor; form: Record<string, string | boolean>; setForm: React.Dispatch<React.SetStateAction<Record<string, string | boolean>>>; stations: CompanyStation[]; editing: boolean; saving: boolean; onClose: () => void; onSave: () => void }) {
  if (!kind) return null;
  const input = (key: string, label: string, keyboardType: 'default' | 'numeric' = 'default') => <View><Text style={styles.fieldLabel}>{label}</Text><TextInput value={String(form[key] ?? '')} onChangeText={value => setForm(current => ({ ...current, [key]: value }))} keyboardType={keyboardType} style={styles.input} placeholderTextColor={Colors.textMuted} /></View>;
  const chips = (key: string, label: string, values: string[]) => <View><Text style={styles.fieldLabel}>{label}</Text><View style={styles.chips}>{values.map(value => <TouchableOpacity key={value} style={[styles.chip, form[key] === value && styles.chipActive]} onPress={() => setForm(current => ({ ...current, [key]: value }))}><Text style={[styles.chipText, form[key] === value && styles.chipTextActive]}>{value}</Text></TouchableOpacity>)}</View></View>;
  return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={styles.modalBackdrop}><ScrollView contentContainerStyle={styles.modalCard}><View style={styles.modalTop}><View><Text style={styles.modalTitle}>{editing ? 'Edit' : 'Add'} {kind}</Text><Text style={styles.modalSub}>Company-owned data and access rules apply.</Text></View><TouchableOpacity style={styles.close} onPress={onClose}><Ionicons name="close" size={20} color={Colors.textSecondary} /></TouchableOpacity></View>{kind === 'station' && <>{input('name','Station name')}{input('city','City')}{input('address','Full address')}{input('latitude','Latitude','numeric')}{input('longitude','Longitude','numeric')}{input('pricePerKwh','Base ₹/kWh','numeric')}{!editing && chips('connectorType','Initial connector',['CCS2','TYPE2','CHADEMO'])}{!editing && input('powerKw','Power kW','numeric')}{input('amenities','Amenities')}{input('workingHours','Working hours')}{input('imageUrl','Photo URL')}</>}{kind === 'charger' && <>{chips('stationId','Station',stations.map(item => String(item.id)))}{input('chargerCode','Charger code')}{chips('connectorType','Connector',['CCS2','TYPE2','CHADEMO'])}{input('powerKw','Power kW','numeric')}{chips('status','Status',['ONLINE','OFFLINE','CHARGING','MAINTENANCE','FAULT'])}{input('firmwareVersion','Firmware version')}{input('healthScore','Health score','numeric')}<View style={styles.switchRow}><Text style={styles.fieldLabel}>Maintenance mode</Text><Switch value={Boolean(form.maintenanceMode)} onValueChange={maintenanceMode => setForm(current => ({ ...current, maintenanceMode }))} /></View></>}{kind === 'pricing' && <>{input('pricePerKwh','Base ₹/kWh','numeric')}{input('timeBasedPricePerHour','Time-based ₹/hour','numeric')}{input('peakPricePerKwh','Peak ₹/kWh','numeric')}{input('peakHours','Peak hours')}{input('studentDiscountPercent','Student discount %','numeric')}{input('corporatePricePerKwh','Corporate ₹/kWh','numeric')}{input('couponCode','Coupon code')}{input('couponDiscountPercent','Coupon discount %','numeric')}<View style={styles.switchRow}><Text style={styles.fieldLabel}>Dynamic pricing</Text><Switch value={Boolean(form.dynamicPricingEnabled)} onValueChange={dynamicPricingEnabled => setForm(current => ({ ...current, dynamicPricingEnabled }))} /></View></>}<View style={styles.modalActions}><PrimaryButton title="Cancel" variant="outline" onPress={onClose} style={styles.modalButton} /><PrimaryButton title="Save" onPress={onSave} loading={saving} style={styles.modalButton} /></View></ScrollView></View></Modal>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background }, content: { padding: 16, paddingBottom: 32 }, segment: { padding: 4, flexDirection: 'row', borderRadius: 14, backgroundColor: '#E8EBF0' }, segmentButton: { flex: 1, minHeight: 39, alignItems: 'center', justifyContent: 'center', borderRadius: 10 }, segmentActive: { backgroundColor: Colors.white }, segmentText: { color: Colors.textSecondary, fontSize: 9.5, fontWeight: '800' }, segmentTextActive: { color: Colors.blue }, search: { height: 47, marginTop: 11, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: Colors.border, borderRadius: 13, backgroundColor: Colors.white }, searchInput: { flex: 1, color: Colors.textPrimary, fontSize: 11.5 },
  card: { minHeight: 94, marginTop: 10, padding: 13, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 17, backgroundColor: Colors.white }, cardIcon: { width: 44, height: 52, marginRight: 11, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blueLight }, cardIconDanger: { backgroundColor: Colors.errorLight }, cardCopy: { flex: 1, minWidth: 0 }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 }, stationName: { flex: 1, color: Colors.textPrimary, fontSize: 12.5, fontWeight: '900' }, stationMeta: { marginTop: 4, color: Colors.textSecondary, fontSize: 8.8 }, stationSub: { marginTop: 5, color: Colors.textMuted, fontSize: 8.2 }, status: { paddingHorizontal: 6, paddingVertical: 3, borderRadius: 7, backgroundColor: Colors.primaryLight }, statusDanger: { backgroundColor: Colors.errorLight }, statusText: { color: Colors.primary, fontSize: 7, fontWeight: '900' }, statusTextDanger: { color: Colors.error }, cardActions: { marginTop: 8, flexDirection: 'row', gap: 14 },
  healthRow: { flexDirection: 'row', justifyContent: 'space-between' }, health: { marginTop: 5, color: Colors.primary, fontSize: 8.2, fontWeight: '800' }, deleteText: { color: Colors.error },
  pricingCard: { marginTop: 10, padding: 15, borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 17, backgroundColor: Colors.white }, pricingTop: { flexDirection: 'row', justifyContent: 'space-between' }, price: { color: Colors.primary, fontSize: 13, fontWeight: '900' }, pricingRow: { marginTop: 14, padding: 12, flexDirection: 'row', justifyContent: 'space-between', borderRadius: 12, backgroundColor: Colors.background }, priceLabel: { color: Colors.textMuted, fontSize: 8 }, priceValue: { marginTop: 3, color: Colors.textPrimary, fontSize: 10, fontWeight: '800' }, editHint: { marginTop: 10, color: Colors.blue, fontSize: 8.5, fontWeight: '700' },
  empty: { marginTop: 12, padding: 30, alignItems: 'center', borderWidth: 1, borderColor: Colors.borderSoft, borderRadius: 18, backgroundColor: Colors.white }, emptyIcon: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.blueLight }, emptyTitle: { marginTop: 12, color: Colors.textPrimary, fontSize: 14, fontWeight: '900' }, emptyText: { marginTop: 4, color: Colors.textSecondary, fontSize: 9.5, textAlign: 'center' }, emptyButton: { minWidth: 170, marginTop: 15 },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16,24,40,.48)' }, modalCard: { maxHeight: '94%', padding: 19, paddingBottom: 30, borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: Colors.white }, modalTop: { marginBottom: 5, flexDirection: 'row', justifyContent: 'space-between' }, modalTitle: { color: Colors.textPrimary, fontSize: 18, fontWeight: '900' }, modalSub: { marginTop: 3, color: Colors.textSecondary, fontSize: 9.5 }, close: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: Colors.border, borderRadius: 10 }, fieldLabel: { marginTop: 13, marginBottom: 6, color: Colors.textPrimary, fontSize: 9.5, fontWeight: '800' }, input: { height: 43, paddingHorizontal: 12, borderWidth: 1, borderColor: Colors.border, borderRadius: 11, color: Colors.textPrimary, fontSize: 11, backgroundColor: Colors.background }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: Colors.border, borderRadius: 9 }, chipActive: { borderColor: Colors.blue, backgroundColor: Colors.blueLight }, chipText: { color: Colors.textSecondary, fontSize: 9, fontWeight: '700' }, chipTextActive: { color: Colors.blue }, switchRow: { marginTop: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, modalActions: { marginTop: 22, flexDirection: 'row', gap: 8 }, modalButton: { flex: 1 },
});
