package com.vidyut.admin.entity;

public enum OperationalControlType {
    RESTRICT_NEW_BOOKINGS,
    FREEZE_PAYMENTS,
    REQUIRE_USER_VERIFICATION,
    TEMPORARILY_RESTRICT_ACCESS,
    PAUSE_NEW_LISTINGS,
    FREEZE_PAYOUTS,
    SUSPEND_NEW_PARTNERSHIPS,
    REQUIRE_SITE_REVERIFICATION,
    PAUSE_COMPANY_BOOKINGS,
    DISABLE_STATION_PUBLISHING,
    FREEZE_SETTLEMENTS,
    SUSPEND_MARKETPLACE_ACCESS,
    REQUIRE_COMPLIANCE_REVIEW
}
