import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Colors } from '../../src/constants/colors';
import { LoadingView } from '../../src/components/LoadingView';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { getSession, paySession, stopSession } from '../../src/features/sessions/session.api';

export default function SessionScreen(){const{id}=useLocalSearchParams<{id:string}>();const client=useQueryClient();const query=useQuery({queryKey:['session',id],queryFn:()=>getSession(id!),enabled:!!id,refetchInterval:q=>q.state.data?.status==='ACTIVE'?10000:false});const stop=useMutation({mutationFn:()=>stopSession(id!),onSuccess:value=>{client.setQueryData(['session',id],value);client.invalidateQueries({queryKey:['bookings']});},onError:(error:Error)=>Alert.alert('Could not stop charging',error.message)});const pay=useMutation({mutationFn:()=>paySession(id!),onSuccess:value=>{client.setQueryData(['session',id],value);client.invalidateQueries({queryKey:['vehicle-wallets']});},onError:(error:Error)=>Alert.alert('Payment not completed',error.message)});if(query.isLoading||!query.data)return <LoadingView message="Reading charger telemetry..."/>;const session=query.data;const progress=Math.max(0,Math.min(100,(session.currentBatteryPercent-session.startBatteryPercent)/Math.max(1,session.targetBatteryPercent-session.startBatteryPercent)*100));const elapsed=Date.now()-new Date(session.startedAt).getTime();const hours=Math.floor(elapsed/3600000);const minutes=Math.floor(elapsed/60000)%60;const seconds=Math.floor(elapsed/1000)%60;return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={[styles.hero,session.status==='COMPLETED'&&styles.heroDone]}><View style={styles.live}><View style={[styles.pulse,session.status==='COMPLETED'&&{backgroundColor:'#BBF7D0'}]}/><Text style={styles.liveText}>{session.status==='ACTIVE'?'LIVE CHARGING':'SESSION COMPLETE'}</Text></View><Text style={styles.percent}>{session.currentBatteryPercent}%</Text><Text style={styles.target}>Target {session.targetBatteryPercent}% • {session.vehicleName||'Your EV'}</Text><View style={styles.track}><View style={[styles.fill,{width:`${progress}%`}]} /></View><Text style={styles.station}>{session.stationName}</Text></View>
<View style={styles.grid}><Metric icon="time-outline" label="Elapsed" value={`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`}/><Metric icon="flash-outline" label="Energy" value={`${session.energyKwh.toFixed(2)} kWh`}/><Metric icon="speedometer-outline" label="Power" value={`${session.powerKw.toFixed(1)} kW`}/><Metric icon="wallet-outline" label="Current cost" value={`₹${session.cost.toFixed(2)}`}/></View>
{session.status==='COMPLETED'?<View style={styles.summary}><Text style={styles.summaryTitle}>Charging summary</Text><Summary label="Energy delivered" value={`${session.energyKwh.toFixed(2)} kWh`}/><Summary label="Total cost" value={`₹${session.cost.toFixed(2)}`}/><Summary label="CO₂ avoided" value={`${session.co2SavedKg.toFixed(2)} kg`}/><Summary label="Payment" value={session.paymentStatus}/>{session.paymentStatus==='DUE'?<PrimaryButton title="Pay from vehicle wallet" onPress={()=>pay.mutate()} loading={pay.isPending} style={{marginTop:15}}/>:<View style={styles.paid}><Ionicons name="checkmark-circle" size={18} color={Colors.success}/><Text style={styles.paidText}>Paid • receipt saved to Wallet</Text></View>}</View>:<><View style={styles.info}><Ionicons name="sync-outline" size={18} color={Colors.primary}/><Text style={styles.infoText}>Meter values refresh every 10 seconds. Battery percentage is estimated unless trusted vehicle telemetry is available.</Text></View><PrimaryButton title="Stop charging" variant="outline" onPress={()=>Alert.alert('Stop charging?','The session will finish and the metered amount becomes payable.',[{text:'Continue charging',style:'cancel'},{text:'Stop',style:'destructive',onPress:()=>stop.mutate()}])} loading={stop.isPending} style={{marginTop:17}}/></>}</ScrollView>}
function Metric({icon,label,value}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string}){return <View style={styles.metric}><Ionicons name={icon} size={20} color={Colors.primary}/><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>};function Summary({label,value}:{label:string;value:string}){return <View style={styles.summaryRow}><Text style={styles.summaryLabel}>{label}</Text><Text style={styles.summaryValue}>{value}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.background},content:{padding:17,paddingBottom:35},hero:{padding:23,borderRadius:22,backgroundColor:'#075B3B'},heroDone:{backgroundColor:'#164E3A'},live:{flexDirection:'row',alignItems:'center',gap:7},pulse:{width:9,height:9,borderRadius:5,backgroundColor:'#4ADE80'},liveText:{color:'#D1FAE5',fontSize:9,fontWeight:'900',letterSpacing:1.2},percent:{marginTop:18,color:Colors.white,fontSize:48,fontWeight:'900'},target:{color:'#A7F3D0',fontSize:10},track:{height:8,marginTop:16,borderRadius:4,backgroundColor:'rgba(255,255,255,.15)',overflow:'hidden'},fill:{height:'100%',borderRadius:4,backgroundColor:'#4ADE80'},station:{marginTop:15,color:Colors.white,fontSize:14,fontWeight:'800'},grid:{marginTop:12,flexDirection:'row',flexWrap:'wrap',gap:9},metric:{width:'48%',padding:15,borderRadius:15,backgroundColor:Colors.white,borderWidth:1,borderColor:Colors.border},metricValue:{marginTop:8,color:Colors.textPrimary,fontSize:16,fontWeight:'900'},metricLabel:{marginTop:2,color:Colors.textSecondary,fontSize:9},info:{marginTop:13,padding:12,flexDirection:'row',gap:8,borderRadius:12,backgroundColor:Colors.primarySoft},infoText:{flex:1,color:Colors.textSecondary,fontSize:9.5,lineHeight:14},summary:{marginTop:14,padding:17,borderRadius:17,backgroundColor:Colors.white,borderWidth:1,borderColor:Colors.border},summaryTitle:{marginBottom:8,color:Colors.textPrimary,fontSize:17,fontWeight:'900'},summaryRow:{paddingVertical:11,flexDirection:'row',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:Colors.borderSoft},summaryLabel:{color:Colors.textSecondary,fontSize:11},summaryValue:{color:Colors.textPrimary,fontSize:11,fontWeight:'900'},paid:{marginTop:14,padding:11,flexDirection:'row',gap:7,justifyContent:'center',borderRadius:11,backgroundColor:Colors.successLight},paidText:{color:Colors.success,fontSize:10,fontWeight:'900'}});
