import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import QRCode from 'react-native-qrcode-svg';
import { Colors } from '../src/constants/colors';
import { LoadingView } from '../src/components/LoadingView';
import { getVehicleWallet } from '../src/features/wallet/wallet.api';

export default function WalletTagScreen(){const{vehicleId}=useLocalSearchParams<{vehicleId:string}>();const query=useQuery({queryKey:['vehicle-wallet',vehicleId],queryFn:()=>getVehicleWallet(Number(vehicleId)),enabled:!!vehicleId});if(query.isLoading||!query.data)return <LoadingView message="Loading charging tag..."/>;const wallet=query.data;return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.icon}><Ionicons name="qr-code-outline" size={27} color={Colors.primary}/></View><Text style={styles.title}>Vehicle charging tag</Text><Text style={styles.subtitle}>Use this tag only at a verified Vidyut charger. It identifies the vehicle wallet; it does not expose a card number.</Text></View><View style={styles.qrCard}><QRCode value={`vidyut://vehicle-wallet/${wallet.tagUid}`} size={230} color="#101828" backgroundColor="#FFFFFF"/><Text style={styles.tag}>{wallet.tagUid}</Text><Text style={styles.vehicle}>{wallet.vehicleName} • {wallet.registrationNumber}</Text></View><View style={styles.balance}><View><Text style={styles.balanceLabel}>AVAILABLE FOR THIS VEHICLE</Text><Text style={styles.balanceValue}>₹{wallet.balance.toFixed(2)}</Text></View><Ionicons name="shield-checkmark-outline" size={29} color="#A7F3D0"/></View><View style={styles.note}><Ionicons name="information-circle-outline" size={18} color={Colors.primary}/><Text style={styles.noteText}>The station must still authenticate your account and confirm the charging session before any wallet debit.</Text></View></ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.background},content:{padding:18,paddingBottom:35},hero:{alignItems:'center'},icon:{width:55,height:55,borderRadius:17,backgroundColor:Colors.primaryLight,alignItems:'center',justifyContent:'center'},title:{marginTop:13,color:Colors.textPrimary,fontSize:22,fontWeight:'900'},subtitle:{marginTop:7,maxWidth:340,color:Colors.textSecondary,fontSize:11,lineHeight:17,textAlign:'center'},qrCard:{marginTop:21,padding:25,alignItems:'center',borderRadius:23,backgroundColor:Colors.white,borderWidth:1,borderColor:Colors.border},tag:{marginTop:18,color:Colors.textPrimary,fontSize:13,fontWeight:'900',letterSpacing:1},vehicle:{marginTop:5,color:Colors.textSecondary,fontSize:10},balance:{marginTop:12,padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderRadius:17,backgroundColor:'#075B3B'},balanceLabel:{color:'#A7F3D0',fontSize:8.5,fontWeight:'900',letterSpacing:.8},balanceValue:{marginTop:5,color:Colors.white,fontSize:25,fontWeight:'900'},note:{marginTop:12,padding:12,flexDirection:'row',gap:8,borderRadius:12,backgroundColor:Colors.primarySoft},noteText:{flex:1,color:Colors.textSecondary,fontSize:9.5,lineHeight:14}});
