import React, { useState } from 'react';
import { FlatList, RefreshControl, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useQuery } from '@tanstack/react-query';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadingView } from '../../src/components/LoadingView';
import { EmptyState } from '../../src/components/EmptyState';
import { Colors } from '../../src/constants/colors';
import { getMyBookings } from '../../src/features/bookings/booking.api';
import { useAuthStore } from '../../src/features/auth/auth.store';

export default function BookingsScreen(){const router=useRouter();const userId=useAuthStore(s=>s.user?.id);const[tab,setTab]=useState<'UPCOMING'|'PAST'>('UPCOMING');const query=useQuery({queryKey:['bookings',userId],queryFn:()=>getMyBookings(userId!),enabled:userId!==undefined,refetchInterval:30000});if(query.isLoading)return <LoadingView message="Loading your bookings..."/>;const data=(query.data??[]).filter(item=>tab==='UPCOMING'?['PENDING','CONFIRMED','IN_PROGRESS'].includes(item.status):['COMPLETED','CANCELLED','EXPIRED'].includes(item.status));return <SafeAreaView style={styles.screen}><AppHeader title="My bookings" subtitle="Reservations, live sessions and receipts"/><View style={styles.tabs}>{(['UPCOMING','PAST'] as const).map(value=><TouchableOpacity key={value} onPress={()=>setTab(value)} style={[styles.tab,tab===value&&styles.tabOn]}><Text style={[styles.tabText,tab===value&&styles.tabTextOn]}>{value==='UPCOMING'?'Upcoming & active':'Past sessions'}</Text></TouchableOpacity>)}</View>{data.length?<FlatList data={data} keyExtractor={item=>String(item.id)} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={query.refetch} colors={[Colors.primary]}/>} renderItem={({item})=><TouchableOpacity style={styles.card} onPress={()=>router.push(`/booking/${item.id}`)}><View style={[styles.icon,item.status==='IN_PROGRESS'&&styles.iconLive]}><Ionicons name={item.status==='IN_PROGRESS'?'pulse':'flash'} size={21} color={item.status==='IN_PROGRESS'?Colors.warning:Colors.primary}/></View><View style={{flex:1}}><Text style={styles.name}>{item.chargerName}</Text><Text numberOfLines={1} style={styles.address}>{item.address}</Text><Text style={styles.time}>{new Date(item.startTime).toLocaleString('en-IN')} • {item.durationMinutes} min</Text><View style={styles.bottom}><Text style={styles.cost}>₹{item.totalCost.toFixed(2)}</Text><View style={[styles.status,{backgroundColor:statusColor(item.status).bg}]}><Text style={[styles.statusText,{color:statusColor(item.status).fg}]}>{item.status.replace('_',' ')}</Text></View></View></View><Ionicons name="chevron-forward" size={18} color={Colors.textMuted}/></TouchableOpacity>}/>:<EmptyState iconName={tab==='UPCOMING'?'calendar-outline':'receipt-outline'} title={tab==='UPCOMING'?'No upcoming bookings':'No past sessions'} subtitle={tab==='UPCOMING'?'Find a compatible charger and reserve your preferred time.':'Completed and cancelled booking records will appear here.'}/>}</SafeAreaView>}
const statusColor=(status:string)=>status==='IN_PROGRESS'?{bg:Colors.warningLight,fg:Colors.warning}:status==='COMPLETED'||status==='CONFIRMED'?{bg:Colors.successLight,fg:Colors.success}:status==='CANCELLED'?{bg:Colors.errorLight,fg:Colors.error}:{bg:Colors.borderSoft,fg:Colors.textSecondary};
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.background},tabs:{margin:13,padding:4,flexDirection:'row',borderRadius:13,backgroundColor:'#E9EDF2'},tab:{flex:1,paddingVertical:10,alignItems:'center',borderRadius:10},tabOn:{backgroundColor:Colors.white},tabText:{color:Colors.textSecondary,fontSize:10,fontWeight:'800'},tabTextOn:{color:Colors.primary},list:{padding:14,paddingBottom:35},card:{marginBottom:10,padding:13,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:Colors.border,borderRadius:16,backgroundColor:Colors.white},icon:{width:42,height:42,borderRadius:13,backgroundColor:Colors.primaryLight,alignItems:'center',justifyContent:'center'},iconLive:{backgroundColor:Colors.warningLight},name:{color:Colors.textPrimary,fontSize:12,fontWeight:'900'},address:{marginTop:2,color:Colors.textSecondary,fontSize:8.5},time:{marginTop:5,color:Colors.textSecondary,fontSize:8.5},bottom:{marginTop:8,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},cost:{color:Colors.textPrimary,fontSize:11,fontWeight:'900'},status:{paddingHorizontal:8,paddingVertical:5,borderRadius:9},statusText:{fontSize:7.5,fontWeight:'900'}});
