ALTER TABLE companies ADD COLUMN IF NOT EXISTS agent_mode VARCHAR(30) NOT NULL DEFAULT 'ASK_BEFORE_ACTIONS';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS agent_max_price_change_percent DOUBLE PRECISION NOT NULL DEFAULT 10;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS agent_auto_disable_faulty_chargers BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS agent_auto_create_maintenance_tickets BOOLEAN NOT NULL DEFAULT TRUE;
