import React, { useState } from 'react';
import { Alert, Modal, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Colors } from '../../src/constants/colors';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { addVehicle, deleteVehicle, getMyVehicles } from '../../src/features/vehicles/vehicle.api';

export default function VehiclesScreen() {
  const client = useQueryClient();
  const [expanded, setExpanded] = useState<number | null>(null);
  const [showAdd, setShowAdd] = useState(false);
  const [form, setForm] = useState({ makeAndModel: '', registrationNumber: '', batteryCapacity: '', connectorType: 'CCS2' });
  const query = useQuery({ queryKey: ['vehicles'], queryFn: getMyVehicles });
  const addMutation = useMutation({ mutationFn: addVehicle, onSuccess: () => { client.invalidateQueries({ queryKey: ['vehicles'] }); setShowAdd(false); setForm({ makeAndModel: '', registrationNumber: '', batteryCapacity: '', connectorType: 'CCS2' }); }, onError: (error: Error) => Alert.alert('Unable to add vehicle', error.message) });
  const remove = (id: number) => Alert.alert('Remove vehicle?', 'The vehicle wallet must have a zero balance before removal.', [{ text: 'Keep', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: async () => { try { await deleteVehicle(id); await client.invalidateQueries({ queryKey: ['vehicles'] }); } catch (error) { Alert.alert('Unable to remove', error instanceof Error ? error.message : 'Please try again.'); } } }]);
  const add = () => {
    if (!form.makeAndModel.trim() || !form.registrationNumber.trim()) { Alert.alert('Vehicle details', 'Make/model and registration number are required.'); return; }
    addMutation.mutate({ ...form, registrationNumber: form.registrationNumber.trim().toUpperCase() });
  };
  return <View style={styles.screen}><ScrollView refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={query.refetch} colors={[Colors.primary]} />} contentContainerStyle={styles.content}>
    <View style={styles.hero}><View><Text style={styles.eyebrow}>YOUR GARAGE</Text><Text style={styles.title}>Connected vehicles</Text><Text style={styles.subtitle}>Tap a vehicle for battery, connectivity and charging history.</Text></View><TouchableOpacity style={styles.add} onPress={() => setShowAdd(true)}><Ionicons name="add" size={20} color={Colors.white} /></TouchableOpacity></View>
    {(query.data ?? []).map(vehicle => { const open = expanded === vehicle.id; const connected = vehicle.connectionStatus === 'CONNECTED'; return <TouchableOpacity activeOpacity={.9} key={vehicle.id} style={styles.card} onPress={() => setExpanded(open ? null : vehicle.id)}>
      <View style={styles.cardTop}><View style={styles.carIcon}><Ionicons name="car-sport" size={25} color={Colors.primary} /></View><View style={styles.cardCopy}><Text style={styles.vehicleName}>{vehicle.makeAndModel}</Text><Text style={styles.reg}>{vehicle.registrationNumber} • {vehicle.connectorType || 'Connector not set'}</Text></View><View style={[styles.status, connected ? styles.connected : styles.disconnected]}><View style={[styles.dot, { backgroundColor: connected ? Colors.success : Colors.textMuted }]} /><Text style={[styles.statusText, { color: connected ? Colors.success : Colors.textSecondary }]}>{connected ? 'Connected' : 'Offline'}</Text></View></View>
      <View style={styles.metrics}><Metric icon="battery-half-outline" label="Battery" value={vehicle.batteryPercent == null ? 'Not available' : `${vehicle.batteryPercent}%`} /><Metric icon="speedometer-outline" label="Range" value={vehicle.remainingRangeKm == null ? 'Not available' : `${Math.round(vehicle.remainingRangeKm)} km`} /><Metric icon="flash-outline" label="State" value={vehicle.charging ? 'Charging' : 'Not charging'} /></View>
      {open ? <View style={styles.details}>
        <Info icon="bluetooth-outline" title="Bluetooth telemetry" value={vehicle.bluetoothSupported ? vehicle.bluetoothDeviceName || 'Supported' : 'Not supported / not shared'} />
        <Info icon="logo-android" title="Android Auto" value={vehicle.androidAutoSupported ? 'Supported' : 'Not reported'} />
        <Info icon="logo-apple" title="Apple CarPlay" value={vehicle.appleCarPlaySupported ? 'Supported' : 'Not reported'} />
        <Info icon="location-outline" title="Last charge" value={vehicle.lastChargingStation ? `${vehicle.lastChargingStation}${vehicle.lastChargedAt ? ` • ${new Date(vehicle.lastChargedAt).toLocaleString()}` : ''}` : 'No completed Vidyut session yet'} />
        <View style={styles.source}><Ionicons name="information-circle-outline" size={16} color={Colors.primary} /><Text style={styles.sourceText}>Battery and range appear only when the vehicle, Bluetooth adapter, Android Auto/CarPlay integration, or station exposes trusted telemetry. Source: {vehicle.telemetrySource || 'NOT_AVAILABLE'}.</Text></View>
        <TouchableOpacity style={styles.remove} onPress={() => remove(vehicle.id)}><Ionicons name="trash-outline" size={16} color={Colors.error} /><Text style={styles.removeText}>Remove vehicle</Text></TouchableOpacity>
      </View> : null}
    </TouchableOpacity>; })}
    {!query.data?.length ? <View style={styles.empty}><Ionicons name="car-outline" size={39} color={Colors.primary} /><Text style={styles.emptyTitle}>Add your first EV</Text><Text style={styles.emptyText}>A vehicle is required before booking so connectors, range and payments stay compatible.</Text><PrimaryButton title="Add vehicle" onPress={() => setShowAdd(true)} style={{ marginTop: 17 }} /></View> : null}
  </ScrollView>
  <Modal visible={showAdd} transparent animationType="slide" onRequestClose={() => setShowAdd(false)}><View style={styles.backdrop}><View style={styles.modal}><View style={styles.modalTop}><Text style={styles.modalTitle}>Add vehicle</Text><TouchableOpacity onPress={() => setShowAdd(false)}><Ionicons name="close" size={23} color={Colors.textSecondary} /></TouchableOpacity></View>
    <Field label="Make and model" value={form.makeAndModel} onChangeText={makeAndModel => setForm(v => ({ ...v, makeAndModel }))} placeholder="Tata Nexon EV Max" /><Field label="Registration number" value={form.registrationNumber} onChangeText={registrationNumber => setForm(v => ({ ...v, registrationNumber }))} placeholder="UP32 AB 1234" autoCapitalize="characters" /><Field label="Battery capacity" value={form.batteryCapacity} onChangeText={batteryCapacity => setForm(v => ({ ...v, batteryCapacity }))} placeholder="40.5 kWh" />
    <Text style={styles.label}>Connector</Text><View style={styles.chips}>{['CCS2', 'TYPE2', 'CHADEMO'].map(type => <TouchableOpacity key={type} style={[styles.chip, form.connectorType === type && styles.chipOn]} onPress={() => setForm(v => ({ ...v, connectorType: type }))}><Text style={[styles.chipText, form.connectorType === type && styles.chipTextOn]}>{type}</Text></TouchableOpacity>)}</View><PrimaryButton title="Save vehicle" onPress={add} loading={addMutation.isPending} style={{ marginTop: 22 }} />
  </View></View></Modal></View>;
}

function Metric({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { return <View style={styles.metric}><Ionicons name={icon} size={18} color={Colors.primary} /><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Info({ icon, title, value }: { icon: keyof typeof Ionicons.glyphMap; title: string; value: string }) { return <View style={styles.info}><Ionicons name={icon} size={18} color={Colors.textSecondary} /><View style={{ flex: 1 }}><Text style={styles.infoTitle}>{title}</Text><Text style={styles.infoValue}>{value}</Text></View></View>; }
function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View><Text style={styles.label}>{label}</Text><TextInput {...props} placeholderTextColor={Colors.textMuted} style={styles.input} /></View>; }
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background }, content: { padding: 17, paddingBottom: 38 }, hero: { marginBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { color: Colors.primary, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 }, title: { marginTop: 5, color: Colors.textPrimary, fontSize: 26, fontWeight: '900' }, subtitle: { marginTop: 4, maxWidth: 300, color: Colors.textSecondary, fontSize: 11 }, add: { width: 45, height: 45, borderRadius: 15, backgroundColor: Colors.primary, alignItems: 'center', justifyContent: 'center' },
  card: { marginBottom: 12, padding: 15, borderRadius: 19, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.white }, cardTop: { flexDirection: 'row', alignItems: 'center' }, carIcon: { width: 46, height: 46, borderRadius: 14, backgroundColor: Colors.primaryLight, alignItems: 'center', justifyContent: 'center' }, cardCopy: { flex: 1, marginLeft: 11 }, vehicleName: { color: Colors.textPrimary, fontSize: 15, fontWeight: '900' }, reg: { marginTop: 3, color: Colors.textSecondary, fontSize: 9.5 }, status: { flexDirection: 'row', gap: 5, alignItems: 'center', paddingHorizontal: 8, paddingVertical: 6, borderRadius: 10 }, connected: { backgroundColor: Colors.successLight }, disconnected: { backgroundColor: Colors.borderSoft }, dot: { width: 6, height: 6, borderRadius: 3 }, statusText: { fontSize: 8.5, fontWeight: '900' },
  metrics: { marginTop: 14, flexDirection: 'row', gap: 7 }, metric: { flex: 1, paddingVertical: 11, alignItems: 'center', borderRadius: 12, backgroundColor: Colors.background }, metricValue: { marginTop: 5, color: Colors.textPrimary, fontSize: 10, fontWeight: '900' }, metricLabel: { marginTop: 2, color: Colors.textMuted, fontSize: 8 }, details: { marginTop: 14, paddingTop: 10, borderTopWidth: 1, borderTopColor: Colors.borderSoft }, info: { paddingVertical: 8, flexDirection: 'row', alignItems: 'center', gap: 10 }, infoTitle: { color: Colors.textSecondary, fontSize: 8.5, fontWeight: '700' }, infoValue: { marginTop: 2, color: Colors.textPrimary, fontSize: 10.5, fontWeight: '700' }, source: { marginTop: 8, padding: 10, flexDirection: 'row', gap: 7, borderRadius: 11, backgroundColor: Colors.primarySoft }, sourceText: { flex: 1, color: Colors.textSecondary, fontSize: 8.5, lineHeight: 13 }, remove: { marginTop: 10, height: 40, flexDirection: 'row', gap: 6, alignItems: 'center', justifyContent: 'center' }, removeText: { color: Colors.error, fontSize: 10, fontWeight: '800' },
  empty: { marginTop: 30, padding: 27, alignItems: 'center', borderRadius: 20, backgroundColor: Colors.white }, emptyTitle: { marginTop: 12, color: Colors.textPrimary, fontSize: 17, fontWeight: '900' }, emptyText: { marginTop: 5, color: Colors.textSecondary, fontSize: 11, lineHeight: 17, textAlign: 'center' }, backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16,24,40,.5)' }, modal: { padding: 20, paddingBottom: 32, borderTopLeftRadius: 25, borderTopRightRadius: 25, backgroundColor: Colors.white }, modalTop: { marginBottom: 6, flexDirection: 'row', justifyContent: 'space-between' }, modalTitle: { color: Colors.textPrimary, fontSize: 20, fontWeight: '900' }, label: { marginTop: 14, marginBottom: 6, color: Colors.textPrimary, fontSize: 10, fontWeight: '800' }, input: { height: 44, borderWidth: 1, borderColor: Colors.border, borderRadius: 11, paddingHorizontal: 12, color: Colors.textPrimary, backgroundColor: Colors.background }, chips: { flexDirection: 'row', gap: 7 }, chip: { paddingHorizontal: 13, paddingVertical: 9, borderWidth: 1, borderColor: Colors.border, borderRadius: 10 }, chipOn: { borderColor: Colors.primary, backgroundColor: Colors.primaryLight }, chipText: { color: Colors.textSecondary, fontSize: 10, fontWeight: '800' }, chipTextOn: { color: Colors.primary },
});
