import React, { useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadingView } from '../../src/components/LoadingView';
import { Colors } from '../../src/constants/colors';
import { getHostBookings, updateHostBooking } from '../../src/features/host/host.api';
import { HostBooking } from '../../src/features/host/host.types';

type BookingFilter = 'UPCOMING' | 'LIVE' | 'HISTORY';
const money = (value:number) => `₹${value.toLocaleString('en-IN')}`;

export default function HostBookingsScreen() {
  const client = useQueryClient();
  const [filter,setFilter] = useState<BookingFilter>('UPCOMING');
  const query = useQuery({ queryKey:['host-bookings'], queryFn:getHostBookings });
  const update = useMutation({ mutationFn:({id,status}:{id:number;status:HostBooking['status']}) => updateHostBooking(id,status), onSuccess:async()=>{ await Promise.all([client.invalidateQueries({queryKey:['host-bookings']}),client.invalidateQueries({queryKey:['host-dashboard']}),client.invalidateQueries({queryKey:['host-earnings']})]); }, onError:(error:Error)=>Alert.alert('Could not update booking',error.message) });
  if(query.isLoading) return <LoadingView message="Loading Host bookings..." />;
  const all=query.data??[];
  const visible=all.filter(item=>filter==='UPCOMING'?['PENDING','CONFIRMED'].includes(item.status):filter==='LIVE'?item.status==='IN_PROGRESS':['COMPLETED','CANCELLED'].includes(item.status));
  const change=(item:HostBooking,status:HostBooking['status'])=>Alert.alert(`${status.replace('_',' ')} booking?`,`${item.customerName} · ${item.stationName}`,[{text:'Cancel',style:'cancel'},{text:'Confirm',onPress:()=>update.mutate({id:item.id,status})}]);
  return <View style={styles.screen}><AppHeader title="Host bookings" subtitle="Reservations, queue and charging sessions" rightIcon="calendar-outline" /><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={query.isRefetching} onRefresh={()=>void query.refetch()} colors={[Colors.primary]} />}>
    <View style={styles.segment}>{(['UPCOMING','LIVE','HISTORY'] as BookingFilter[]).map(item=><TouchableOpacity key={item} style={[styles.segmentButton,filter===item&&styles.segmentActive]} onPress={()=>setFilter(item)}><Text style={[styles.segmentText,filter===item&&styles.segmentTextActive]}>{item==='UPCOMING'?'Upcoming':item==='LIVE'?'Live':'History'}</Text></TouchableOpacity>)}</View>
    <View style={styles.summary}><View><Text style={styles.summaryValue}>{visible.length}</Text><Text style={styles.summaryLabel}>{filter==='LIVE'?'active charging sessions':filter==='HISTORY'?'completed or cancelled':'bookings needing attention'}</Text></View><View style={styles.summaryIcon}><Ionicons name={filter==='LIVE'?'flash':'calendar'} size={21} color={Colors.primary}/></View></View>
    {visible.map(item=><View key={item.id} style={styles.card}><View style={styles.cardTop}><View style={styles.avatar}><Ionicons name="person-outline" size={19} color={Colors.primary}/></View><View style={styles.copy}><Text style={styles.name}>{item.customerName}</Text><Text style={styles.email}>{item.customerEmail}</Text></View><Text style={styles.amount}>{money(item.totalAmount)}</Text></View><View style={styles.line}/><Text style={styles.station}>{item.stationName}</Text><View style={styles.details}><Text style={styles.detailText}>{new Date(item.startTime).toLocaleString('en-IN')}</Text><Text style={styles.detailText}>{item.durationHours}h · {item.kwhDelivered} kWh</Text><Text style={styles.status}>{item.status}</Text></View><View style={styles.actions}>{item.status==='PENDING'&&<><Action text="Accept" onPress={()=>change(item,'CONFIRMED')}/><Action text="Reject" danger onPress={()=>change(item,'CANCELLED')}/></>}{item.status==='CONFIRMED'&&<><Action text="Start charging" onPress={()=>change(item,'IN_PROGRESS')}/><Action text="Cancel" danger onPress={()=>change(item,'CANCELLED')}/></>}{item.status==='IN_PROGRESS'&&<Action text="Complete & receive payment" onPress={()=>change(item,'COMPLETED')}/>}</View></View>)}
    {!visible.length&&<View style={styles.empty}><Ionicons name="calendar-clear-outline" size={30} color={Colors.textMuted}/><Text>No {filter.toLowerCase()} bookings.</Text></View>}
  </ScrollView></View>;
}
function Action({text,onPress,danger=false}:{text:string;onPress:()=>void;danger?:boolean}){return <TouchableOpacity style={[styles.action,danger&&styles.actionDanger]} onPress={onPress}><Text style={[styles.actionText,danger&&styles.actionTextDanger]}>{text}</Text></TouchableOpacity>}
const styles=StyleSheet.create({
  screen:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:32},segment:{padding:4,flexDirection:'row',borderRadius:14,backgroundColor:'#EDEFF3'},segmentButton:{flex:1,minHeight:40,alignItems:'center',justifyContent:'center',borderRadius:11},segmentActive:{backgroundColor:Colors.white},segmentText:{color:Colors.textSecondary,fontSize:10,fontWeight:'800'},segmentTextActive:{color:Colors.primary},summary:{marginTop:14,padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderRadius:17,backgroundColor:Colors.secondary},summaryValue:{color:Colors.white,fontSize:24,fontWeight:'900'},summaryLabel:{marginTop:3,color:'#98A2B3',fontSize:10},summaryIcon:{width:44,height:44,borderRadius:14,justifyContent:'center',alignItems:'center',backgroundColor:'#E8F7F0'},card:{marginTop:12,padding:15,borderWidth:1,borderColor:Colors.borderSoft,borderRadius:17,backgroundColor:Colors.white},cardTop:{flexDirection:'row',alignItems:'center'},avatar:{width:40,height:40,marginRight:11,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:Colors.primaryLight},copy:{flex:1},name:{color:Colors.textPrimary,fontSize:13,fontWeight:'900'},email:{marginTop:3,color:Colors.textSecondary,fontSize:9},amount:{color:Colors.textPrimary,fontSize:14,fontWeight:'900'},line:{height:1,marginVertical:11,backgroundColor:Colors.borderSoft},station:{color:Colors.textPrimary,fontSize:10.5,fontWeight:'800'},details:{marginTop:6,flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:7},detailText:{color:Colors.textSecondary,fontSize:8.5},status:{paddingHorizontal:6,paddingVertical:3,borderRadius:7,overflow:'hidden',color:Colors.primary,backgroundColor:Colors.primaryLight,fontSize:7,fontWeight:'900'},actions:{marginTop:11,flexDirection:'row',gap:7},action:{paddingHorizontal:12,paddingVertical:8,borderRadius:9,backgroundColor:Colors.primaryLight},actionDanger:{backgroundColor:Colors.errorLight},actionText:{color:Colors.primary,fontSize:8.5,fontWeight:'900'},actionTextDanger:{color:Colors.error},empty:{minHeight:210,alignItems:'center',justifyContent:'center',gap:8},
});
