import React, { useState } from 'react';
import { Alert, Modal, RefreshControl, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '../../src/components/AppHeader';
import { LoadingView } from '../../src/components/LoadingView';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { Colors } from '../../src/constants/colors';
import { createHostStation, deleteHostStation, getHostMonitoring, getHostProfile, getHostStations, updateHostAvailability, updateHostConnector, updateHostStation } from '../../src/features/host/host.api';
import { HostMonitor, HostStation } from '../../src/features/host/host.types';

type Segment = 'CHARGERS' | 'AVAILABILITY' | 'MONITORING';
type Editor = 'charger' | 'availability' | null;

export default function HostStationsScreen() {
  const client = useQueryClient();
  const [segment, setSegment] = useState<Segment>('CHARGERS');
  const [editor, setEditor] = useState<Editor>(null);
  const [editing, setEditing] = useState<HostStation | null>(null);
  const [form, setForm] = useState<Record<string, string | boolean>>({});
  const stationsQuery = useQuery({ queryKey: ['host-stations'], queryFn: getHostStations });
  const monitorQuery = useQuery({ queryKey: ['host-monitoring'], queryFn: getHostMonitoring });
  const profileQuery = useQuery({ queryKey: ['host-profile'], queryFn: getHostProfile });
  const invalidate = async () => { await Promise.all([client.invalidateQueries({ queryKey: ['host-stations'] }), client.invalidateQueries({ queryKey: ['host-monitoring'] }), client.invalidateQueries({ queryKey: ['host-dashboard'] })]); };
  const save = useMutation({ mutationFn: async () => {
    if (editor === 'availability' && editing) return updateHostAvailability(editing.id, { availability: form.availability, weeklySchedule: form.weeklySchedule, holidaySchedule: form.holidaySchedule, chargingInstructions: form.chargingInstructions, bookingSlotMinutes: Number(form.bookingSlotMinutes), autoAvailability: Boolean(form.autoAvailability), emergencyDisabled: Boolean(form.emergencyDisabled) });
    const body = { ...form, latitude: Number(form.latitude), longitude: Number(form.longitude), pricePerKwh: Number(form.pricePerKwh), powerKw: Number(form.powerKw), bookingSlotMinutes: 60 };
    return editing ? updateHostStation(editing.id, body) : createHostStation(body);
  }, onSuccess: async () => { setEditor(null); setEditing(null); await invalidate(); Alert.alert('Saved', 'Your private charger setup is updated.'); }, onError: (error: Error) => Alert.alert('Could not save', error.message) });
  const remove = useMutation({ mutationFn: deleteHostStation, onSuccess: invalidate, onError: (error: Error) => Alert.alert('Could not delete', error.message) });
  const status = useMutation({ mutationFn: ({ item, value }: { item: HostMonitor; value: HostMonitor['status'] }) => updateHostConnector(item.id, { status: value, currentPowerKw: value === 'CHARGING' ? item.powerKw : 0, sessionEnergyKwh: item.sessionEnergyKwh, healthScore: item.healthScore, faultCode: value === 'FAULT' ? item.faultCode || 'HOST_REPORTED' : null }), onSuccess: invalidate, onError: (error: Error) => Alert.alert('Could not update status', error.message) });

  const openCharger = (station?: HostStation) => { const verified = profileQuery.data?.emailVerified && profileQuery.data.verificationStatus === 'VERIFIED'; if (!verified) { Alert.alert('Verification required', 'Verify email and KYC before registering or changing a charger.'); return; } setEditing(station ?? null); setEditor('charger'); setForm(station ? { name: station.name, city: station.city, address: station.address, latitude: String(station.latitude), longitude: String(station.longitude), pricePerKwh: String(station.pricePerKwh), imageUrl: station.imageUrl ?? '', photoUrls: station.photoUrls ?? '', amenities: station.amenities ?? '', workingHours: station.workingHours ?? '', chargingInstructions: station.chargingInstructions ?? '', status: station.status, availability: station.availability } : { name: '', city: '', address: '', latitude: '26.8467', longitude: '80.9462', pricePerKwh: '16', connectorType: 'TYPE2', powerKw: '7.4', imageUrl: '', photoUrls: '', amenities: 'Parking', workingHours: '06:00-23:00', chargingInstructions: '' }); };
  const openAvailability = (station: HostStation) => { setEditing(station); setEditor('availability'); setForm({ availability: station.availability, weeklySchedule: station.weeklySchedule ?? 'MON-SUN 06:00-23:00', holidaySchedule: station.holidaySchedule ?? '', chargingInstructions: station.chargingInstructions ?? '', bookingSlotMinutes: String(station.bookingSlotMinutes || 60), autoAvailability: station.autoAvailability, emergencyDisabled: station.emergencyDisabled }); };
  if (stationsQuery.isLoading || monitorQuery.isLoading || profileQuery.isLoading) return <LoadingView message="Loading private chargers..." />;
  const stations = stationsQuery.data ?? []; const monitoring = monitorQuery.data ?? []; const refreshing = stationsQuery.isRefetching || monitorQuery.isRefetching;
  return <View style={styles.screen}>
    <AppHeader title="My chargers" subtitle="Setup, availability and live health" rightIcon="add" onRightPress={() => openCharger()} />
    <ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { void stationsQuery.refetch(); void monitorQuery.refetch(); }} colors={[Colors.primary]} />}>
      <View style={styles.segment}>{(['CHARGERS','AVAILABILITY','MONITORING'] as Segment[]).map(item => <TouchableOpacity key={item} style={[styles.segmentButton, segment === item && styles.segmentActive]} onPress={() => setSegment(item)}><Text style={[styles.segmentText, segment === item && styles.segmentTextActive]}>{item === 'CHARGERS' ? 'Chargers' : item === 'AVAILABILITY' ? 'Schedule' : 'Live health'}</Text></TouchableOpacity>)}</View>
      {segment === 'CHARGERS' && <>{stations.map(item => <StationCard key={item.id} item={item} onEdit={() => openCharger(item)} onSchedule={() => openAvailability(item)} onDelete={() => Alert.alert('Delete charger?', 'Its private listing and connectors will be removed.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => remove.mutate(item.id) }])} />)}{!stations.length && <Empty title="No private chargers" text="Register your first charger after Host verification." onPress={() => openCharger()} />}</>}
      {segment === 'AVAILABILITY' && <>{stations.map(item => <TouchableOpacity key={item.id} style={styles.scheduleCard} onPress={() => openAvailability(item)}><View style={styles.rowTop}><Text style={styles.title}>{item.name}</Text><Status value={item.emergencyDisabled ? 'EMERGENCY OFF' : item.availability} danger={item.emergencyDisabled} /></View><Text style={styles.meta}>{item.weeklySchedule || item.workingHours || 'Schedule not set'}</Text><Text style={styles.sub}>{item.holidaySchedule || 'No holiday exceptions'} · {item.bookingSlotMinutes || 60} minute slots</Text><View style={styles.auto}><Ionicons name="sync-outline" size={14} color={Colors.primary} /><Text style={styles.autoText}>Auto availability {item.autoAvailability ? 'on' : 'off'}</Text></View></TouchableOpacity>)}{!stations.length && <Empty title="No schedule yet" text="Add a charger before setting availability." onPress={() => openCharger()} />}</>}
      {segment === 'MONITORING' && <>{monitoring.map(item => <MonitorCard key={item.id} item={item} onStatus={value => status.mutate({ item, value })} />)}{!monitoring.length && <Empty title="No live connectors" text="Monitoring starts when a charger is registered." onPress={() => openCharger()} />}</>}
    </ScrollView>
    <EditorModal kind={editor} form={form} setForm={setForm} editing={Boolean(editing)} saving={save.isPending} onClose={() => setEditor(null)} onSave={() => save.mutate()} />
  </View>;
}

function StationCard({ item, onEdit, onSchedule, onDelete }: { item: HostStation; onEdit: () => void; onSchedule: () => void; onDelete: () => void }) { const c = item.connectors?.[0]; return <View style={styles.card}><View style={styles.icon}><Ionicons name="flash-outline" size={21} color={Colors.primary} /></View><View style={styles.copy}><View style={styles.rowTop}><Text style={styles.title}>{item.name}</Text><Status value={item.availability} /></View><Text style={styles.meta}>{item.city} · {item.address}</Text><Text style={styles.sub}>{c?.type ?? 'Connector'} · {c?.powerKw ?? 0} kW · ₹{item.pricePerKwh}/kWh</Text><View style={styles.actions}><TouchableOpacity onPress={onSchedule}><Text style={styles.actionText}>Schedule</Text></TouchableOpacity><TouchableOpacity onPress={onEdit}><Text style={styles.actionText}>Edit</Text></TouchableOpacity><TouchableOpacity onPress={onDelete}><Text style={[styles.actionText, styles.delete]}>Delete</Text></TouchableOpacity></View></View></View>; }
function MonitorCard({ item, onStatus }: { item: HostMonitor; onStatus: (value: HostMonitor['status']) => void }) { return <View style={styles.monitorCard}><View style={styles.rowTop}><View><Text style={styles.title}>{item.chargerCode}</Text><Text style={styles.meta}>{item.stationName} · {item.connectorType} · {item.powerKw} kW</Text></View><Status value={item.status} danger={item.status === 'FAULT'} /></View><View style={styles.monitorStats}><Mini label="Power" value={`${item.currentPowerKw} kW`} /><Mini label="Energy" value={`${item.sessionEnergyKwh} kWh`} /><Mini label="Duration" value={`${item.sessionDurationMinutes} min`} /><Mini label="Health" value={`${item.healthScore}%`} /></View>{item.faultCode && <Text style={styles.fault}>⚠ {item.faultCode}</Text>}<View style={styles.statusButtons}>{(['ONLINE','OFFLINE','CHARGING','MAINTENANCE','FAULT'] as HostMonitor['status'][]).map(value => <TouchableOpacity key={value} style={[styles.statusButton, item.status === value && styles.statusButtonActive]} onPress={() => onStatus(value)}><Text style={[styles.statusButtonText, item.status === value && styles.statusButtonTextActive]}>{value}</Text></TouchableOpacity>)}</View></View>; }
function Status({ value, danger = false }: { value: string; danger?: boolean }) { return <View style={[styles.badge, danger && styles.badgeDanger]}><Text style={[styles.badgeText, danger && styles.badgeTextDanger]}>{value}</Text></View>; }
function Mini({ label, value }: { label: string; value: string }) { return <View><Text style={styles.miniLabel}>{label}</Text><Text style={styles.miniValue}>{value}</Text></View>; }
function Empty({ title, text, onPress }: { title: string; text: string; onPress: () => void }) { return <View style={styles.empty}><Ionicons name="flash-outline" size={28} color={Colors.primary} /><Text style={styles.emptyTitle}>{title}</Text><Text style={styles.emptyText}>{text}</Text><PrimaryButton title="Add charger" onPress={onPress} style={{ marginTop: 15, minWidth: 180 }} /></View>; }

function EditorModal({ kind, form, setForm, editing, saving, onClose, onSave }: { kind: Editor; form: Record<string,string|boolean>; setForm: React.Dispatch<React.SetStateAction<Record<string,string|boolean>>>; editing: boolean; saving: boolean; onClose: () => void; onSave: () => void }) { if (!kind) return null; const input = (key:string,label:string,numeric=false) => <View><Text style={styles.label}>{label}</Text><TextInput value={String(form[key] ?? '')} onChangeText={value => setForm(current => ({ ...current, [key]: value }))} keyboardType={numeric ? 'numeric' : 'default'} style={styles.input} /></View>; const chips = (key:string,label:string,values:string[]) => <View><Text style={styles.label}>{label}</Text><View style={styles.chips}>{values.map(value => <TouchableOpacity key={value} style={[styles.chip,form[key]===value&&styles.chipActive]} onPress={() => setForm(current => ({...current,[key]:value}))}><Text style={[styles.chipText,form[key]===value&&styles.chipTextActive]}>{value}</Text></TouchableOpacity>)}</View></View>; return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><ScrollView contentContainerStyle={styles.modal}><View style={styles.modalHead}><Text style={styles.modalTitle}>{kind === 'availability' ? 'Availability schedule' : `${editing ? 'Edit' : 'Register'} charger`}</Text><TouchableOpacity onPress={onClose}><Ionicons name="close" size={21} color={Colors.textSecondary} /></TouchableOpacity></View>{kind === 'charger' && <>{input('name','Charger name')}{input('city','City')}{input('address','Full address')}{input('latitude','Latitude',true)}{input('longitude','Longitude',true)}{input('pricePerKwh','Price ₹/kWh',true)}{!editing && chips('connectorType','Connector',['TYPE2','CCS2','CHADEMO','GB_T'])}{!editing && input('powerKw','Charging speed kW',true)}{input('imageUrl','Primary photo URL')}{input('photoUrls','More photo URLs')}{input('amenities','Amenities')}{input('workingHours','Working hours')}{input('chargingInstructions','Customer instructions')}</>}{kind === 'availability' && <>{chips('availability','Availability',['AVAILABLE','RESERVED','UNAVAILABLE'])}{input('weeklySchedule','Weekly schedule')}{input('holidaySchedule','Holiday exceptions')}{input('bookingSlotMinutes','Slot minutes',true)}{input('chargingInstructions','Charging instructions')}<Toggle label="Auto availability" value={Boolean(form.autoAvailability)} onChange={value => setForm(current => ({...current,autoAvailability:value}))} /><Toggle label="Emergency disable" value={Boolean(form.emergencyDisabled)} onChange={value => setForm(current => ({...current,emergencyDisabled:value}))} danger /></>}<View style={styles.modalActions}><PrimaryButton title="Cancel" variant="outline" onPress={onClose} style={{flex:1}} /><PrimaryButton title="Save" onPress={onSave} loading={saving} style={{flex:1}} /></View></ScrollView></View></Modal>; }
function Toggle({ label, value, onChange, danger=false }: { label:string; value:boolean; onChange:(value:boolean)=>void; danger?:boolean }) { return <View style={styles.toggle}><Text style={[styles.label,danger&&{color:Colors.error}]}>{label}</Text><Switch value={value} onValueChange={onChange} trackColor={{false:'#D0D5DD',true:danger?'#FDA29B':'#8DD9BA'}} /></View>; }

const styles = StyleSheet.create({
  screen:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:32},segment:{padding:4,flexDirection:'row',borderRadius:14,backgroundColor:'#E8EBF0'},segmentButton:{flex:1,minHeight:39,alignItems:'center',justifyContent:'center',borderRadius:10},segmentActive:{backgroundColor:Colors.white},segmentText:{color:Colors.textSecondary,fontSize:9,fontWeight:'800'},segmentTextActive:{color:Colors.primary},
  card:{marginTop:11,padding:14,flexDirection:'row',borderWidth:1,borderColor:Colors.borderSoft,borderRadius:17,backgroundColor:Colors.white},icon:{width:45,height:55,marginRight:11,alignItems:'center',justifyContent:'center',borderRadius:13,backgroundColor:Colors.primaryLight},copy:{flex:1,minWidth:0},rowTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},title:{flexShrink:1,color:Colors.textPrimary,fontSize:12.5,fontWeight:'900'},meta:{marginTop:4,color:Colors.textSecondary,fontSize:9},sub:{marginTop:5,color:Colors.textMuted,fontSize:8.5},actions:{marginTop:10,flexDirection:'row',gap:16},actionText:{color:Colors.primary,fontSize:9,fontWeight:'800'},delete:{color:Colors.error},badge:{paddingHorizontal:7,paddingVertical:4,borderRadius:8,backgroundColor:Colors.primaryLight},badgeDanger:{backgroundColor:Colors.errorLight},badgeText:{color:Colors.primary,fontSize:7,fontWeight:'900'},badgeTextDanger:{color:Colors.error},
  scheduleCard:{marginTop:11,padding:15,borderWidth:1,borderColor:Colors.borderSoft,borderRadius:17,backgroundColor:Colors.white},auto:{marginTop:10,flexDirection:'row',alignItems:'center',gap:5},autoText:{color:Colors.primary,fontSize:8.5,fontWeight:'800'},monitorCard:{marginTop:11,padding:15,borderWidth:1,borderColor:Colors.borderSoft,borderRadius:17,backgroundColor:Colors.white},monitorStats:{marginTop:13,padding:11,flexDirection:'row',justifyContent:'space-between',borderRadius:12,backgroundColor:Colors.primarySoft},miniLabel:{color:Colors.textMuted,fontSize:7.5},miniValue:{marginTop:3,color:Colors.textPrimary,fontSize:9.5,fontWeight:'900'},fault:{marginTop:9,color:Colors.error,fontSize:9,fontWeight:'800'},statusButtons:{marginTop:11,flexDirection:'row',flexWrap:'wrap',gap:5},statusButton:{paddingHorizontal:7,paddingVertical:6,borderRadius:8,backgroundColor:Colors.background},statusButtonActive:{backgroundColor:Colors.primary},statusButtonText:{color:Colors.textSecondary,fontSize:6.5,fontWeight:'800'},statusButtonTextActive:{color:Colors.white},
  empty:{marginTop:12,padding:30,alignItems:'center',borderWidth:1,borderColor:Colors.borderSoft,borderRadius:18,backgroundColor:Colors.white},emptyTitle:{marginTop:10,color:Colors.textPrimary,fontSize:14,fontWeight:'900'},emptyText:{marginTop:4,color:Colors.textSecondary,fontSize:9.5,textAlign:'center'},backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(16,24,40,.48)'},modal:{padding:19,paddingBottom:30,borderTopLeftRadius:24,borderTopRightRadius:24,backgroundColor:Colors.white},modalHead:{marginBottom:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},modalTitle:{color:Colors.textPrimary,fontSize:18,fontWeight:'900'},label:{marginTop:10,color:Colors.textPrimary,fontSize:9.5,fontWeight:'800'},input:{height:43,marginTop:6,paddingHorizontal:11,borderWidth:1,borderColor:Colors.border,borderRadius:11,color:Colors.textPrimary},chips:{marginTop:7,flexDirection:'row',flexWrap:'wrap',gap:6},chip:{paddingHorizontal:9,paddingVertical:7,borderRadius:9,backgroundColor:Colors.background},chipActive:{backgroundColor:Colors.primary},chipText:{color:Colors.textSecondary,fontSize:8,fontWeight:'800'},chipTextActive:{color:Colors.white},toggle:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},modalActions:{marginTop:18,flexDirection:'row',gap:9},
});
