import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Colors } from '../../src/constants/colors';
import { PrimaryButton } from '../../src/components/PrimaryButton';
import { LoadingView } from '../../src/components/LoadingView';
import { cancelBooking, getBooking } from '../../src/features/bookings/booking.api';
import { startSession } from '../../src/features/sessions/session.api';
import { getRouteStatus, divertBooking } from '../../src/features/routing/routing.api';

export default function BookingDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router=useRouter(); const client=useQueryClient();
  const booking=useQuery({queryKey:['booking',id],queryFn:()=>getBooking(id!),enabled:!!id,refetchInterval:30000});
  const route=useQuery({queryKey:['route-status',id],queryFn:()=>getRouteStatus(Number(id)),enabled:!!id&&['PENDING','CONFIRMED'].includes(booking.data?.status||''),refetchInterval:30000});
  const cancel=useMutation({mutationFn:()=>cancelBooking(id!),onSuccess:value=>{client.setQueryData(['booking',id],value);client.invalidateQueries({queryKey:['bookings']});},onError:(error:Error)=>Alert.alert('Cancellation failed',error.message)});
  const start=useMutation({mutationFn:()=>startSession(id!),onSuccess:value=>{client.invalidateQueries({queryKey:['bookings']});router.push(`/session/${value.id}`);},onError:(error:Error)=>Alert.alert('Could not start charging',error.message)});
  if(booking.isLoading||!booking.data)return <LoadingView message="Loading booking details..."/>; const item=booking.data;
  const confirmCancel=()=>Alert.alert('Cancel this booking?', 'Free until 2 hours before start; later cancellation may charge 10%.',[{text:'Keep booking',style:'cancel'},{text:'Cancel booking',style:'destructive',onPress:()=>cancel.mutate()}]);
  const divert=async(stationId:number)=>{try{await divertBooking(Number(id),stationId);await client.invalidateQueries({queryKey:['bookings']});Alert.alert('Booking diverted','Your replacement booking is ready in My Bookings.');router.replace('/(owner)/bookings');}catch(error){Alert.alert('Diversion failed',error instanceof Error?error.message:'Please try again.')}};
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.hero}><View style={styles.heroIcon}><Ionicons name="flash" size={28} color={Colors.primary}/></View><Text style={styles.station}>{item.chargerName}</Text><Text style={styles.address}>{item.address}</Text><View style={styles.status}><Text style={styles.statusText}>{item.status.replace('_',' ')}</Text></View></View>
    {route.data?.diversionRecommended?<View style={styles.diversion}><View style={styles.diversionTop}><Ionicons name="warning-outline" size={21} color={Colors.warning}/><View style={{flex:1}}><Text style={styles.diversionTitle}>Station conditions changed</Text><Text style={styles.diversionText}>{route.data.reason}</Text></View></View>{route.data.alternatives.slice(0,2).map(stop=><TouchableOpacity key={stop.station.id} style={styles.alternative} onPress={()=>divert(Number(stop.station.id))}><View><Text style={styles.altName}>{stop.station.name}</Text><Text style={styles.altMeta}>{stop.detourKm} km detour • {stop.availableSlots} free • ₹{stop.station.pricePerKwh}/kWh</Text></View><Ionicons name="arrow-forward" size={17} color={Colors.primary}/></TouchableOpacity>)}</View>:null}
    <View style={styles.card}><Row label="Starts" value={new Date(item.startTime).toLocaleString('en-IN')}/><Row label="Ends" value={item.endTime?new Date(item.endTime).toLocaleString('en-IN'):`${item.durationMinutes} min`}/><Row label="Duration" value={`${item.durationMinutes} minutes`}/><Row label="Estimated energy" value={`${(item.kwhDelivered||0).toFixed(1)} kWh`}/>{item.outletTierName?<Row label="Outlet rate" value={`${item.outletTierName} · ₹${item.appliedRatePerKwh?.toFixed(2)}/kWh`}/>:null}<Row label="Estimated total" value={`₹${item.totalCost.toFixed(2)}`}/>{item.status==='CANCELLED'?<><Row label="Cancellation fee" value={`₹${(item.cancellationFee||0).toFixed(2)}`}/><Row label="Refund" value={`₹${(item.refundAmount||0).toFixed(2)}`}/></>:null}</View>
    <View style={styles.note}><Ionicons name="information-circle-outline" size={18} color={Colors.primary}/><Text style={styles.noteText}>Start charging when you are connected at the station. Live energy, battery estimate and cost update every 10 seconds.</Text></View>
    {['PENDING','CONFIRMED'].includes(item.status)?<PrimaryButton title="Navigate and monitor station" variant="outline" onPress={()=>router.push(`/active-trip/${item.id}`)} style={{marginTop:14}}/>:null}
    {['PENDING','CONFIRMED'].includes(item.status)?<View style={styles.actions}><PrimaryButton title="Cancel" variant="outline" onPress={confirmCancel} loading={cancel.isPending} style={{flex:1}}/><PrimaryButton title="Start charging" onPress={()=>start.mutate()} loading={start.isPending} style={{flex:2}}/></View>:null}
  </ScrollView>;
}
function Row({label,value}:{label:string;value:string}){return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:Colors.background},content:{padding:17,paddingBottom:35},hero:{padding:23,alignItems:'center',borderRadius:20,backgroundColor:Colors.white,borderWidth:1,borderColor:Colors.border},heroIcon:{width:56,height:56,borderRadius:17,backgroundColor:Colors.primaryLight,alignItems:'center',justifyContent:'center'},station:{marginTop:12,color:Colors.textPrimary,fontSize:20,fontWeight:'900'},address:{marginTop:4,color:Colors.textSecondary,fontSize:11,textAlign:'center'},status:{marginTop:12,paddingHorizontal:12,paddingVertical:6,borderRadius:11,backgroundColor:Colors.primaryLight},statusText:{color:Colors.primary,fontSize:9,fontWeight:'900'},card:{marginTop:14,overflow:'hidden',borderRadius:17,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.white},row:{padding:15,flexDirection:'row',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:Colors.borderSoft},label:{color:Colors.textSecondary,fontSize:11},value:{maxWidth:'60%',color:Colors.textPrimary,fontSize:11,fontWeight:'900',textAlign:'right'},note:{marginTop:13,padding:12,flexDirection:'row',gap:8,borderRadius:12,backgroundColor:Colors.primarySoft},noteText:{flex:1,color:Colors.textSecondary,fontSize:9.5,lineHeight:14},actions:{marginTop:18,flexDirection:'row',gap:8},diversion:{marginTop:14,padding:14,borderRadius:16,borderWidth:1,borderColor:'#FED7AA',backgroundColor:'#FFF7ED'},diversionTop:{flexDirection:'row',gap:9},diversionTitle:{color:'#9A3412',fontSize:12,fontWeight:'900'},diversionText:{marginTop:2,color:'#9A3412',fontSize:9.5},alternative:{marginTop:9,padding:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderRadius:11,backgroundColor:Colors.white},altName:{color:Colors.textPrimary,fontSize:10.5,fontWeight:'900'},altMeta:{marginTop:2,color:Colors.textSecondary,fontSize:8}});
